-- Battery specifications, conformed to CATEGORY_SPEC_FIELDS.batteries.
--
-- GENERATED by the script named at the end of this file — edit that, re-run
-- it, do not hand-patch this.
--
-- Lead-acid and lithium share one field set. A float voltage reads null on
-- a lithium pack and a discharge cut-off reads null on a flooded cell — that is
-- the chemistry answering, not the record being incomplete.
--
-- Every batteries row ends up with the same 32 keys. A value the
-- datasheet does not state is null, which a query can count; a MISSING key
-- cannot be counted, and that is the whole point of a declared field set.

-- ICAL LIP12100D 12V/100Ah
-- source: LIP12100D Deep Cycle datasheet MKT.MY.032024
-- note: lead-acid despite the LIP model prefix — see the charge voltages
update "3.0_components"
set specifications = coalesce(specifications, '{}'::jsonb) || '{
  "battery_type": "Lead-acid (deep cycle)",
  "nominal_voltage_v": 12,
  "rated_capacity_ah": 100,
  "energy_wh": 1200,
  "charge_voltage_cycle_v": 14.4,
  "charge_voltage_float_v": 13.8,
  "rated_charge_current_a": 30,
  "max_discharge_current_a": 800,
  "internal_resistance_mohm": 5,
  "self_discharge_percent_per_month": "~3 (91% of capacity after 3 months)",
  "dimensions_l_w_h_mm": "407 x 174 x 236 (total height with terminals)",
  "weight_kg": 32.5,
  "terminal_type": "Bolt, 8mm"
}'::jsonb
where component_id = '5aaf8efd-e790-4ae8-bf8c-123b48dfb5f1';

-- ICAL LIP12200D 12V/200Ah
-- source: LIP12200D Deep Cycle datasheet
-- note: lead-acid despite the LIP model prefix
update "3.0_components"
set specifications = coalesce(specifications, '{}'::jsonb) || '{
  "battery_type": "Lead-acid (deep cycle)",
  "nominal_voltage_v": 12,
  "rated_capacity_ah": 200,
  "energy_wh": 2400,
  "charge_voltage_cycle_v": 14.4,
  "charge_voltage_float_v": 13.8,
  "internal_resistance_mohm": 3,
  "self_discharge_percent_per_month": "~3 (91% of capacity after 3 months)",
  "dimensions_l_w_h_mm": "523 x 240 x 230 (total height with terminals)",
  "weight_kg": 57.5,
  "terminal_type": "Bolt, 8mm"
}'::jsonb
where component_id = 'a702ab94-b76a-4de9-a5a1-ef169d8ad9dc';

-- ICAL LIP48100LF 48V/100Ah 15S1P LiFePO4
-- source: LIP48100LF datasheet
update "3.0_components"
set specifications = coalesce(specifications, '{}'::jsonb) || '{
  "battery_type": "LiFePO4 (with BMS)",
  "configuration": "15S1P",
  "nominal_voltage_v": 48,
  "rated_capacity_ah": 100,
  "minimal_capacity_ah": 100,
  "energy_wh": 4800,
  "charge_voltage_v": 54,
  "discharge_cut_off_voltage_v": 39,
  "rated_charge_current_a": 30,
  "max_charge_current_a": 100,
  "max_discharge_current_a": 100,
  "cycle_life": "≥4000 cycles @ 25°C 0.2C/0.2C 80% DOD",
  "internal_resistance_mohm": "≤30 @ 50% SOC 1kHz",
  "self_discharge_percent_per_month": "<3",
  "operating_temp_range_charge_c": "0 to 50",
  "operating_temp_range_discharge_c": "-20 to 55",
  "storage_temp_range_c": "0 to 40",
  "ip_rating": "IP54",
  "dimensions_l_w_h_mm": "450 x 483 x 133",
  "weight_kg": 42,
  "case_material": "Sheet metal shell",
  "certifications": [
    "UN38.3",
    "MSDS"
  ]
}'::jsonb
where component_id = '066ce835-45b4-4643-8a67-9d708e1728bf';

-- EPEVER LR51100A 51.2V/100Ah LiFePO4
-- source: LR51100 A/B/E series datasheet — the A column
-- note: nominal voltage corrected from the stored 48V to the datasheet 51.2V
update "3.0_components"
set specifications = coalesce(specifications, '{}'::jsonb) || '{
  "battery_type": "LiFePO4",
  "configuration": "16S1P",
  "nominal_voltage_v": 51.2,
  "rated_capacity_ah": 100,
  "energy_wh": 5120,
  "charge_voltage_v": 57.6,
  "discharge_cut_off_voltage_v": 41.6,
  "max_charge_current_a": 100,
  "max_discharge_current_a": 100,
  "recommended_discharge_current_a": 50,
  "recommended_depth_of_discharge_percent": 80,
  "max_parallel_units": 32,
  "cycle_life": ">6000 cycles @ 25°C 0.5C 80% DOD",
  "operating_temp_range_charge_c": "0 to 50",
  "operating_temp_range_discharge_c": "-20 to 50",
  "storage_temp_range_c": "5 to 35",
  "humidity_range_percent": "40 to 80",
  "ip_rating": "IP21",
  "dimensions_l_w_h_mm": "476 x 450 x 136",
  "terminal_type": "M8",
  "mounting": "Rack-mounted 3U",
  "communication": "RS485, CAN",
  "display": "LCD",
  "certifications": [
    "UN38.3",
    "MSDS",
    "IEC 62619",
    "RoHS",
    "CE"
  ]
}'::jsonb
where component_id = '88e6cdae-3421-47fa-89a5-506138c6edf3';

-- ── Every other batteries: reshape only, values untouched ──

-- 1. Column data never belongs in the blob (lib/specSchema NON_SPEC_KEYS) — it
--    would also leak a brand onto a customer-facing spec annex.
update "3.0_components"
set specifications = specifications - 'model' - 'brand' - 'selling_price_idr'
where category::text = 'batteries'
  and specifications ?| array['model', 'brand', 'selling_price_idr'];

-- 2. Add every declared key the row does not carry, as null.
update "3.0_components" c
set specifications = coalesce((
      select jsonb_object_agg(k, 'null'::jsonb)
      from unnest(array['battery_type', 'configuration', 'nominal_voltage_v', 'rated_capacity_ah', 'minimal_capacity_ah', 'energy_wh', 'charge_voltage_v', 'charge_voltage_cycle_v', 'charge_voltage_float_v', 'discharge_cut_off_voltage_v', 'rated_charge_current_a', 'max_charge_current_a', 'max_discharge_current_a', 'recommended_discharge_current_a', 'recommended_depth_of_discharge_percent', 'max_parallel_units', 'cycle_life', 'internal_resistance_mohm', 'self_discharge_percent_per_month', 'operating_temp_range_charge_c', 'operating_temp_range_discharge_c', 'storage_temp_range_c', 'humidity_range_percent', 'ip_rating', 'dimensions_l_w_h_mm', 'weight_kg', 'terminal_type', 'case_material', 'mounting', 'communication', 'display', 'certifications']) as k
      where not (coalesce(c.specifications, '{}'::jsonb) ? k)
    ), '{}'::jsonb) || coalesce(c.specifications, '{}'::jsonb)
where c.category::text = 'batteries';

-- Solar charge controller specifications, conformed to CATEGORY_SPEC_FIELDS.solar_charge_controller.
--
-- GENERATED by the script named at the end of this file — edit that, re-run
-- it, do not hand-patch this.
--
-- MPPT and PWM share one field set: a PWM unit answers null where the
-- tracking questions are, which is the honest way to say "it does not track".
--
-- Every solar_charge_controller row ends up with the same 31 keys. A value the
-- datasheet does not state is null, which a query can count; a MISSING key
-- cannot be counted, and that is the whole point of a declared field set.

-- EPEVER XTRA1210N-G3 MPPT 10A
-- source: XTRA-N G3 / G3 BLE series datasheet, technical specifications table
update "3.0_components"
set specifications = coalesce(specifications, '{}'::jsonb) || '{
  "controller_type": "MPPT",
  "system_voltage_v": "12/24 auto",
  "controller_operating_voltage_range_v": "8 ~ 31",
  "rated_charge_current_a": 10,
  "rated_discharge_current_a": 10,
  "rated_charging_power_w": "130W/12V; 260W/24V",
  "pv_max_voc_v": 100,
  "mppt_voltage_range_v": "(Battery voltage + 2V) ~ 72",
  "max_conversion_efficiency_percent": 98.2,
  "max_load_efficiency_percent": 96.2,
  "tracking_efficiency_percent": "≥99.5",
  "discharge_circuit_voltage_drop_v": "≤0.23",
  "temperature_compensation": "-3mV/°C/2V (default)",
  "grounding_type": "Common negative",
  "battery_types": "Lithium, gel, sealed",
  "communication": "RS485 (5VDC/200mA, RJ45); Bluetooth on the BLE models",
  "dimensions_mm": "175 x 143 x 48",
  "mounting_size_mm": "120 x 134",
  "terminal_mm2": 4,
  "recommended_cable_mm2": 4,
  "weight_kg": 0.59,
  "ip_rating": "IP33",
  "operating_temperature_range_c": "-25 to 50",
  "storage_temperature_range_c": "-20 to 70",
  "humidity_range_percent": "≤95 (non-condensing)",
  "pollution_degree": "PD2",
  "certifications": [
    "CE",
    "IECS"
  ]
}'::jsonb
where component_id = 'a7277c9d-60e3-476f-9f5e-1134676c2b99';

-- EPEVER XTRA2210N-G3 MPPT 20A
-- source: XTRA-N G3 / G3 BLE series datasheet, technical specifications table
update "3.0_components"
set specifications = coalesce(specifications, '{}'::jsonb) || '{
  "controller_type": "MPPT",
  "system_voltage_v": "12/24 auto",
  "controller_operating_voltage_range_v": "8 ~ 31",
  "rated_charge_current_a": 20,
  "rated_discharge_current_a": 20,
  "rated_charging_power_w": "260W/12V; 520W/24V",
  "pv_max_voc_v": 100,
  "mppt_voltage_range_v": "(Battery voltage + 2V) ~ 72",
  "max_conversion_efficiency_percent": 98.3,
  "max_load_efficiency_percent": 96.4,
  "tracking_efficiency_percent": "≥99.5",
  "discharge_circuit_voltage_drop_v": "≤0.23",
  "temperature_compensation": "-3mV/°C/2V (default)",
  "grounding_type": "Common negative",
  "battery_types": "Lithium, gel, sealed",
  "communication": "RS485 (5VDC/200mA, RJ45); Bluetooth on the BLE models",
  "dimensions_mm": "217 x 158 x 56.5",
  "mounting_size_mm": "160 x 149",
  "terminal_mm2": 16,
  "recommended_cable_mm2": 6,
  "weight_kg": 0.97,
  "ip_rating": "IP33",
  "operating_temperature_range_c": "-25 to 50",
  "storage_temperature_range_c": "-20 to 70",
  "humidity_range_percent": "≤95 (non-condensing)",
  "pollution_degree": "PD2",
  "certifications": [
    "CE",
    "IECS"
  ]
}'::jsonb
where component_id = 'c0d60322-1e0f-4daa-9fc6-443e23f735d9';

-- EPEVER XTRA3210N-G3 MPPT 30A
-- source: XTRA-N G3 / G3 BLE series datasheet, technical specifications table
update "3.0_components"
set specifications = coalesce(specifications, '{}'::jsonb) || '{
  "controller_type": "MPPT",
  "system_voltage_v": "12/24 auto",
  "controller_operating_voltage_range_v": "8 ~ 31",
  "rated_charge_current_a": 30,
  "rated_discharge_current_a": 30,
  "rated_charging_power_w": "390W/12V; 780W/24V",
  "pv_max_voc_v": 100,
  "mppt_voltage_range_v": "(Battery voltage + 2V) ~ 72",
  "max_conversion_efficiency_percent": 98.6,
  "max_load_efficiency_percent": 96.6,
  "tracking_efficiency_percent": "≥99.5",
  "discharge_circuit_voltage_drop_v": "≤0.23",
  "temperature_compensation": "-3mV/°C/2V (default)",
  "grounding_type": "Common negative",
  "battery_types": "Lithium, gel, sealed",
  "communication": "RS485 (5VDC/200mA, RJ45); Bluetooth on the BLE models",
  "dimensions_mm": "230 x 165 x 63",
  "mounting_size_mm": "173 x 156",
  "terminal_mm2": 16,
  "recommended_cable_mm2": 10,
  "weight_kg": 1.3,
  "ip_rating": "IP33",
  "operating_temperature_range_c": "-25 to 50",
  "storage_temperature_range_c": "-20 to 70",
  "humidity_range_percent": "≤95 (non-condensing)",
  "pollution_degree": "PD2",
  "certifications": [
    "CE",
    "IECS"
  ]
}'::jsonb
where component_id = '3ef54ee2-af0d-494f-942a-b875c743a083';

-- EPEVER XTRA4210N-G3 MPPT 40A
-- source: XTRA-N G3 / G3 BLE series datasheet, technical specifications table
update "3.0_components"
set specifications = coalesce(specifications, '{}'::jsonb) || '{
  "controller_type": "MPPT",
  "system_voltage_v": "12/24 auto",
  "controller_operating_voltage_range_v": "8 ~ 31",
  "rated_charge_current_a": 40,
  "rated_discharge_current_a": 40,
  "rated_charging_power_w": "520W/12V; 1040W/24V",
  "pv_max_voc_v": 100,
  "mppt_voltage_range_v": "(Battery voltage + 2V) ~ 72",
  "max_conversion_efficiency_percent": 98.6,
  "max_load_efficiency_percent": 96.5,
  "tracking_efficiency_percent": "≥99.5",
  "discharge_circuit_voltage_drop_v": "≤0.23",
  "temperature_compensation": "-3mV/°C/2V (default)",
  "grounding_type": "Common negative",
  "battery_types": "Lithium, gel, sealed",
  "communication": "RS485 (5VDC/200mA, RJ45); Bluetooth on the BLE models",
  "dimensions_mm": "255 x 185 x 67.8",
  "mounting_size_mm": "200 x 176",
  "terminal_mm2": 16,
  "recommended_cable_mm2": 16,
  "weight_kg": 1.72,
  "ip_rating": "IP33",
  "operating_temperature_range_c": "-25 to 50",
  "storage_temperature_range_c": "-20 to 70",
  "humidity_range_percent": "≤95 (non-condensing)",
  "pollution_degree": "PD2",
  "certifications": [
    "CE",
    "IECS"
  ]
}'::jsonb
where component_id = '37631729-7433-4639-97a7-9ae40804b87c';

-- EPEVER XTRA4215N-G3 MPPT 40A
-- source: XTRA-N G3 / G3 BLE series datasheet, technical specifications table
update "3.0_components"
set specifications = coalesce(specifications, '{}'::jsonb) || '{
  "controller_type": "MPPT",
  "system_voltage_v": "12/24 auto",
  "controller_operating_voltage_range_v": "8 ~ 31",
  "rated_charge_current_a": 40,
  "rated_discharge_current_a": 40,
  "rated_charging_power_w": "520W/12V; 1040W/24V",
  "pv_max_voc_v": 150,
  "mppt_voltage_range_v": "(Battery voltage + 2V) ~ 108",
  "max_conversion_efficiency_percent": 97.9,
  "max_load_efficiency_percent": 95.4,
  "tracking_efficiency_percent": "≥99.5",
  "discharge_circuit_voltage_drop_v": "≤0.23",
  "temperature_compensation": "-3mV/°C/2V (default)",
  "grounding_type": "Common negative",
  "battery_types": "Lithium, gel, sealed",
  "communication": "RS485 (5VDC/200mA, RJ45); Bluetooth on the BLE models",
  "dimensions_mm": "255 x 187 x 75.7",
  "mounting_size_mm": "200 x 178",
  "terminal_mm2": 16,
  "recommended_cable_mm2": 16,
  "weight_kg": 2.08,
  "ip_rating": "IP33",
  "operating_temperature_range_c": "-25 to 45",
  "storage_temperature_range_c": "-20 to 70",
  "humidity_range_percent": "≤95 (non-condensing)",
  "pollution_degree": "PD2",
  "certifications": [
    "CE",
    "IECS"
  ]
}'::jsonb
where component_id = '9c8f7486-7b5f-4cf3-8314-d986ccf62710';

-- EPEVER XTRA4415N-G3 MPPT 40A
-- source: XTRA-N G3 / G3 BLE series datasheet, technical specifications table
update "3.0_components"
set specifications = coalesce(specifications, '{}'::jsonb) || '{
  "controller_type": "MPPT",
  "system_voltage_v": "12/24/36/48 auto",
  "controller_operating_voltage_range_v": "8 ~ 62",
  "rated_charge_current_a": 40,
  "rated_discharge_current_a": 40,
  "rated_charging_power_w": "520W/12V; 1040W/24V; 1560W/36V; 2080W/48V",
  "pv_max_voc_v": 150,
  "mppt_voltage_range_v": "(Battery voltage + 2V) ~ 108",
  "max_conversion_efficiency_percent": 98.5,
  "max_load_efficiency_percent": 97.2,
  "tracking_efficiency_percent": "≥99.5",
  "discharge_circuit_voltage_drop_v": "≤0.23",
  "temperature_compensation": "-3mV/°C/2V (default)",
  "grounding_type": "Common negative",
  "battery_types": "Lithium, gel, sealed",
  "communication": "RS485 (5VDC/200mA, RJ45); Bluetooth on the BLE models",
  "dimensions_mm": "255 x 189 x 83.2",
  "mounting_size_mm": "200 x 180",
  "terminal_mm2": 16,
  "recommended_cable_mm2": 16,
  "weight_kg": 2.6,
  "ip_rating": "IP33",
  "operating_temperature_range_c": "-25 to 45",
  "storage_temperature_range_c": "-20 to 70",
  "humidity_range_percent": "≤95 (non-condensing)",
  "pollution_degree": "PD2",
  "certifications": [
    "CE",
    "IECS"
  ]
}'::jsonb
where component_id = 'e8deff05-f4b3-4b64-9ac7-fec2945217ad';

-- ── Every other solar_charge_controller: reshape only, values untouched ──

-- 1. Column data never belongs in the blob (lib/specSchema NON_SPEC_KEYS) — it
--    would also leak a brand onto a customer-facing spec annex.
update "3.0_components"
set specifications = specifications - 'model' - 'brand' - 'selling_price_idr'
where category::text = 'solar_charge_controller'
  and specifications ?| array['model', 'brand', 'selling_price_idr'];

-- 2. Fold the spellings that predate the field set into their canonical names.
update "3.0_components"
set specifications = (specifications - 'battery_temp_compensation' - 'type' - 'rated_current_a' - 'max_pv_voc_v' - 'battery_voltage_v')
  || jsonb_strip_nulls(jsonb_build_object(
       'temperature_compensation', specifications -> 'battery_temp_compensation',
       'controller_type', specifications -> 'type',
       'rated_charge_current_a', specifications -> 'rated_current_a',
       'pv_max_voc_v', specifications -> 'max_pv_voc_v',
       'system_voltage_v', specifications -> 'battery_voltage_v'
     ))
where category::text = 'solar_charge_controller'
  and specifications ?| array['battery_temp_compensation', 'type', 'rated_current_a', 'max_pv_voc_v', 'battery_voltage_v'];

-- 3. Add every declared key the row does not carry, as null.
update "3.0_components" c
set specifications = coalesce((
      select jsonb_object_agg(k, 'null'::jsonb)
      from unnest(array['controller_type', 'system_voltage_v', 'controller_operating_voltage_range_v', 'rated_charge_current_a', 'rated_discharge_current_a', 'rated_charging_power_w', 'pv_max_voc_v', 'mppt_voltage_range_v', 'max_conversion_efficiency_percent', 'max_load_efficiency_percent', 'tracking_efficiency_percent', 'self_consumption_ma', 'discharge_circuit_voltage_drop_v', 'temperature_compensation', 'grounding_type', 'battery_types', 'parallel_operation', 'pv_inputs', 'communication', 'display', 'dimensions_mm', 'mounting_size_mm', 'terminal_mm2', 'recommended_cable_mm2', 'weight_kg', 'ip_rating', 'operating_temperature_range_c', 'storage_temperature_range_c', 'humidity_range_percent', 'pollution_degree', 'certifications']) as k
      where not (coalesce(c.specifications, '{}'::jsonb) ? k)
    ), '{}'::jsonb) || coalesce(c.specifications, '{}'::jsonb)
where c.category::text = 'solar_charge_controller';

-- Generated by scripts/battery-scc-specs.mjs
