-- Inverter-charger specifications, conformed to CATEGORY_SPEC_FIELDS.inverter_charger.
--
-- GENERATED by the script named at the end of this file — edit that, re-run
-- it, do not hand-patch this.
--
-- Forty-seven inverter chargers carried between 0 and 26 keys each: most
-- held only rated_output_power_w and a battery voltage, seven held nothing at
-- all, and one (SNV-GH30081) held a full transcription. Off-grid and hybrid
-- units share one field set — a hybrid is an off-grid inverter that can also
-- export, and the grid block reading null on an off-grid unit is itself the
-- answer to "can this export?".
--
-- Every inverter_charger row ends up with the same 44 keys. A value the
-- datasheet does not state is null, which a query can count; a MISSING key
-- cannot be counted, and that is the whole point of a declared field set.

-- VOLTRONIC Axpert VM 1K-24  ·  ICA SOLAR SNV-GF1021 1kW/24V
-- source: SNV-GF1021 datasheet MKT.PRM/MY/III/2021
-- note: dimensions are stated W*L*D on this sheet, D*W*H on the others
update "3.0_components"
set specifications = coalesce(specifications, '{}'::jsonb) || '{
  "system_type": "Off-grid",
  "rated_output_power_w": 1000,
  "rated_output_power_va": 1000,
  "surge_power_va": 2000,
  "nominal_output_voltage_vac": 220,
  "output_voltage_regulation_vac": "220 ±5%",
  "waveform": "Pure sine wave",
  "transfer_time_ms": "10 (personal computers) / 20 (home appliances)",
  "max_conversion_efficiency_dc_ac_percent": 93,
  "ac_input_voltage_vac": 220,
  "ac_input_voltage_range_vac": "170~280 (personal computers) / 90~280 (home appliances)",
  "ac_input_frequency_range_hz": "50/60 (auto sensing)",
  "max_ac_charging_current_a": 20,
  "pv_solar_charger_type": "MPPT",
  "pv_max_input_power_w": 1000,
  "pv_max_open_circuit_voltage_vdc": 102,
  "pv_mppt_voltage_range_vdc": "30~80",
  "max_solar_charging_current_a": 40,
  "battery_nominal_voltage_vdc": 24,
  "floating_charge_voltage_vdc": 27,
  "overcharge_protection_vdc": 31,
  "max_total_charging_current_a": 60,
  "dimensions_d_w_h_mm": "88 x 225 x 320 (stated W x L x D)",
  "weight_kg": 5,
  "communication_interfaces": "USB / RS232",
  "humidity_range_percent": "5 to 95 (non-condensing)",
  "operating_temperature_range_c": "-10 to 50",
  "storage_temperature_range_c": "-15 to 60"
}'::jsonb
where component_id = '88611ef2-3ae1-4f36-b784-6fedf6b7c200';

-- VOLTRONIC Axpert MKS5 Twin 6.5K  ·  ICA SOLAR SNV-GF6541 6.5kW/48V
-- source: SNV-GF6541 datasheet
-- note: rated 6.5kVA/6.5kW with PV+battery, 6kVA/6kW on battery alone
update "3.0_components"
set specifications = coalesce(specifications, '{}'::jsonb) || '{
  "system_type": "Off-grid",
  "rated_output_power_w": 6500,
  "rated_output_power_va": 6500,
  "overload_capability": "5s @ ≥150% load; 10s @ 110~150% load; 100ms @ ≥200% load",
  "nominal_output_voltage_vac": 230,
  "output_voltage_regulation_vac": "230 ±5%",
  "waveform": "Pure sine wave",
  "transfer_time_ms": "10 (personal computers) / 20 (home appliances)",
  "max_conversion_efficiency_dc_ac_percent": 93,
  "ac_input_voltage_vac": 230,
  "ac_input_voltage_range_vac": "170~280 (personal computers) / 90~280 (home appliances)",
  "ac_input_frequency_range_hz": "50/60 (auto sensing)",
  "max_ac_charging_current_a": 120,
  "pv_solar_charger_type": "MPPT",
  "pv_max_input_power_w": 9000,
  "pv_max_open_circuit_voltage_vdc": 500,
  "pv_mppt_voltage_range_vdc": "90~450",
  "max_pv_input_current_a": 27,
  "max_solar_charging_current_a": 120,
  "battery_nominal_voltage_vdc": 48,
  "floating_charge_voltage_vdc": 54,
  "overcharge_protection_vdc": 66,
  "max_total_charging_current_a": 120,
  "dimensions_d_w_h_mm": "140 x 295 x 468",
  "weight_kg": 12,
  "communication_interfaces": "RS232 / RS485 / WiFi",
  "humidity_range_percent": "5 to 95 (non-condensing)",
  "operating_temperature_range_c": "-10 to 50",
  "storage_temperature_range_c": "-15 to 60"
}'::jsonb
where component_id = 'f2fd5a15-dc8b-419d-abf5-051f657f5827';

-- VOLTRONIC Infinisolar VII 2K-48  ·  ICA SOLAR SNV-GH2041 2kW/48V
-- source: SNV-GH2041 datasheet MKT.PRM/MY/III/2023
update "3.0_components"
set specifications = coalesce(specifications, '{}'::jsonb) || '{
  "system_type": "Hybrid",
  "phase": "1-phase in / 1-phase out",
  "parallel_operation": "Yes, up to 9 units",
  "no_of_mpp_trackers": 1,
  "rated_output_power_w": 2000,
  "nominal_output_voltage_vac": "220/230/240",
  "nominal_output_frequency_hz": 50,
  "waveform": "Pure Sine Wave",
  "efficiency_dc_to_ac_percent": 93,
  "max_conversion_efficiency_dc_ac_percent": 95,
  "grid_output_voltage_range_vac": "184~264.5 or 195.5~253 (selectable)",
  "grid_output_frequency_range_hz": "47.5~51.5 or 49~51 (selectable)",
  "grid_nominal_output_current_a": 8.7,
  "power_factor": ">0.99",
  "ac_input_voltage_range_vac": "90~280 or 170~280",
  "ac_input_frequency_range_hz": "50/60 (auto sensing)",
  "max_ac_input_current_a": 30,
  "max_ac_charging_current_a": 60,
  "pv_max_input_power_w": 3000,
  "pv_nominal_voltage_vdc": 240,
  "pv_max_open_circuit_voltage_vdc": 450,
  "pv_mppt_voltage_range_vdc": "90~430",
  "max_pv_input_current_a": 13,
  "max_solar_charging_current_a": 60,
  "battery_nominal_voltage_vdc": 48,
  "max_total_charging_current_a": 60,
  "dimensions_d_w_h_mm": "120 x 295 x 468",
  "weight_kg": 11,
  "communication_interfaces": "USB or RS-232 / Dry contact",
  "humidity_range_percent": "0~90 (non-condensing)",
  "operating_temperature_range_c": "-10 to 50"
}'::jsonb
where component_id = '8701cc63-133f-4a10-86c2-8881b823e090';

-- VOLTRONIC Infinisolar VII 3K-48  ·  ICA SOLAR SNV-GH3041 3kW/48V
-- source: SNV-GH3041 datasheet MKT.PRM/MY/III/2021
update "3.0_components"
set specifications = coalesce(specifications, '{}'::jsonb) || '{
  "system_type": "Hybrid",
  "phase": "1-phase in / 1-phase out",
  "parallel_operation": "Yes, up to 9 units",
  "no_of_mpp_trackers": 1,
  "rated_output_power_w": 3000,
  "nominal_output_voltage_vac": "220/230/240",
  "nominal_output_frequency_hz": 50,
  "waveform": "Pure Sine Wave",
  "efficiency_dc_to_ac_percent": 93,
  "max_conversion_efficiency_dc_ac_percent": 95,
  "grid_output_voltage_range_vac": "184~264.5 or 195.5~253 (selectable)",
  "grid_output_frequency_range_hz": "47.5~51.5 or 49~51 (selectable)",
  "grid_nominal_output_current_a": 13,
  "power_factor": ">0.99",
  "ac_input_voltage_range_vac": "90~280 or 170~280",
  "ac_input_frequency_range_hz": "50/60 (auto sensing)",
  "max_ac_input_current_a": 40,
  "max_ac_charging_current_a": 60,
  "pv_max_input_power_w": 4000,
  "pv_nominal_voltage_vdc": 360,
  "pv_max_open_circuit_voltage_vdc": 450,
  "pv_mppt_voltage_range_vdc": "120~430",
  "max_pv_input_current_a": 18,
  "max_solar_charging_current_a": 60,
  "battery_nominal_voltage_vdc": 48,
  "max_total_charging_current_a": 60,
  "dimensions_d_w_h_mm": "120 x 295 x 468",
  "weight_kg": 11,
  "communication_interfaces": "USB or RS-232 / Dry contact",
  "humidity_range_percent": "0~90 (non-condensing)",
  "operating_temperature_range_c": "-10 to 50"
}'::jsonb
where component_id = 'd9b72daa-9adb-408d-9398-49a8cd83513b';

-- VOLTRONIC Infinisolar VIII 5K  ·  ICA SOLAR SNV-GH5042 5kW/48V
-- source: SNV-GH5042 datasheet
-- note: GH5041 (Infinisolar VII 5K-48) is a different unit and has no sheet here
update "3.0_components"
set specifications = coalesce(specifications, '{}'::jsonb) || '{
  "system_type": "Hybrid",
  "phase": "1-phase in / 1-phase out",
  "parallel_operation": "Yes, up to 9 units",
  "no_of_mpp_trackers": 1,
  "rated_output_power_w": 5000,
  "nominal_output_voltage_vac": "220/230/240",
  "nominal_output_frequency_hz": 50,
  "waveform": "Pure Sine Wave",
  "efficiency_dc_to_ac_percent": 93,
  "max_conversion_efficiency_dc_ac_percent": 95,
  "grid_output_voltage_range_vac": "184~264.5 or 195.5~253 (selectable)",
  "grid_output_frequency_range_hz": "47.5~51.5 or 49~51 (selectable)",
  "grid_nominal_output_current_a": 21.7,
  "power_factor": ">0.99",
  "ac_input_voltage_range_vac": "90~280 or 170~280",
  "ac_input_frequency_range_hz": "50/60 (auto sensing)",
  "max_ac_input_current_a": 40,
  "max_ac_charging_current_a": 100,
  "pv_max_input_power_w": 6000,
  "pv_nominal_voltage_vdc": 360,
  "pv_max_open_circuit_voltage_vdc": 450,
  "pv_mppt_voltage_range_vdc": "120~430",
  "max_pv_input_current_a": 27,
  "max_solar_charging_current_a": 100,
  "battery_nominal_voltage_vdc": 48,
  "max_total_charging_current_a": 100,
  "dimensions_d_w_h_mm": "140 x 295 x 468",
  "weight_kg": 12,
  "communication_interfaces": "USB or RS-232 / Dry contact; inbuilt WiFi monitoring data logger",
  "humidity_range_percent": "0~90 (non-condensing)",
  "operating_temperature_range_c": "-10 to 50"
}'::jsonb
where component_id = '253bafd9-d00b-42a8-b299-68f97bbd5f85';

-- ── Every other inverter_charger: reshape only, values untouched ──
--
-- The other 42 rows keep every value they had; only the key set changes.
-- Several store `phase` as a number (1) and one as a string ("3-phase") —
-- a value inconsistency the field set does not fix. Left alone deliberately:
-- rewriting values is not what a reshape is for.

-- 1. Column data never belongs in the blob (lib/specSchema NON_SPEC_KEYS) — it
--    would also leak a brand onto a customer-facing spec annex.
update "3.0_components"
set specifications = specifications - 'model' - 'brand' - 'selling_price_idr'
where category::text = 'inverter_charger'
  and specifications ?| array['model', 'brand', 'selling_price_idr'];

-- 2. Fold the spellings that predate the field set into their canonical names.
update "3.0_components"
set specifications = (specifications - 'rated_power_kw' - 'battery_voltage_v' - 'max_charging_current_a' - 'efficiency_percent')
  || jsonb_strip_nulls(jsonb_build_object(
       'rated_output_power_w', specifications -> 'rated_power_kw',
       'battery_nominal_voltage_vdc', specifications -> 'battery_voltage_v',
       'max_total_charging_current_a', specifications -> 'max_charging_current_a',
       'max_conversion_efficiency_dc_ac_percent', specifications -> 'efficiency_percent'
     ))
where category::text = 'inverter_charger'
  and specifications ?| array['rated_power_kw', 'battery_voltage_v', 'max_charging_current_a', 'efficiency_percent'];

-- 3. Add every declared key the row does not carry, as null.
update "3.0_components" c
set specifications = coalesce((
      select jsonb_object_agg(k, 'null'::jsonb)
      from unnest(array['system_type', 'phase', 'parallel_operation', 'no_of_mpp_trackers', 'rated_output_power_w', 'rated_output_power_va', 'surge_power_va', 'overload_capability', 'nominal_output_voltage_vac', 'output_voltage_regulation_vac', 'nominal_output_frequency_hz', 'waveform', 'transfer_time_ms', 'efficiency_dc_to_ac_percent', 'max_conversion_efficiency_dc_ac_percent', 'grid_output_voltage_range_vac', 'grid_output_frequency_range_hz', 'grid_nominal_output_current_a', 'power_factor', 'ac_start_up_voltage_vac', 'ac_input_voltage_vac', 'ac_input_voltage_range_vac', 'ac_input_frequency_range_hz', 'max_ac_input_current_a', 'max_ac_charging_current_a', 'pv_solar_charger_type', 'pv_max_input_power_w', 'pv_nominal_voltage_vdc', 'pv_max_open_circuit_voltage_vdc', 'pv_mppt_voltage_range_vdc', 'max_pv_input_current_a', 'max_solar_charging_current_a', 'battery_nominal_voltage_vdc', 'battery_voltage_range_vdc', 'floating_charge_voltage_vdc', 'overcharge_protection_vdc', 'max_total_charging_current_a', 'dimensions_d_w_h_mm', 'weight_kg', 'communication_interfaces', 'intelligent_slot', 'humidity_range_percent', 'operating_temperature_range_c', 'storage_temperature_range_c']) as k
      where not (coalesce(c.specifications, '{}'::jsonb) ? k)
    ), '{}'::jsonb) || coalesce(c.specifications, '{}'::jsonb)
where c.category::text = 'inverter_charger';

-- Generated by scripts/inverter-charger-specs.mjs
