-- PV module specifications, conformed to CATEGORY_SPEC_FIELDS.pv_module.
--
-- GENERATED by scripts/pv-module-specs.mjs — edit the script, re-run it, do
-- not hand-patch this file.
--
-- Two things happen here, and they are separate:
--
--   1. Every pv_module row is CONFORMED: the 41 declared keys, in declared
--      order, null where the datasheet does not say. Values already stored are
--      kept; legacy spellings (glass_description, power_tolerance_w, the three
--      packing_container_40ft_* keys) fold into their canonical names. This is
--      a reshape, not a rewrite.
--
--   2. Six rows are REPLACED from the datasheets the owner supplied on
--      2026-09-03. Those are listed one by one below with their source.
--
-- Why every key on every row: before this, one TRINA row carried three keys
-- and one ICA row carried thirty. A query cannot tell a missing KEY from a
-- missing VALUE, so "which modules have no NOCT data?" was unanswerable. With
-- the key always present and null meaning "the datasheet does not say", it is
-- one WHERE clause.

-- ICA SOLAR ICA100-36M 100Wp Mono (890x580x28)
-- source: ICA100-36M datasheet MKT.PRM/MY/I/2024 V.03
update "3.0_components"
set specifications = coalesce(specifications, '{}'::jsonb) || '{
  "cell_type": "Monocrystalline",
  "power_stc_w": 100,
  "power_tolerance": "±5%",
  "vmp_stc_v": 22.97,
  "imp_stc_a": 4.36,
  "voc_stc_v": 26.91,
  "isc_stc_a": 4.61,
  "efficiency_percent": 19.37,
  "noct_c": "45 ± 2",
  "temp_coeff_pmax_percent_per_c": -0.45,
  "temp_coeff_voc_percent_per_c": -0.32,
  "temp_coeff_isc_percent_per_c": 0.06,
  "max_system_voltage_vdc": 1000,
  "max_series_fuse_a": 15,
  "operating_temp_range_c": "-45 to +80",
  "dimensions_l_w_h_mm": "890 x 580 x 28",
  "weight_kg": 5.9,
  "certifications": [
    "LSPr-072-IDN",
    "SNI IEC 61215-1-1:2016",
    "SNI IEC 61215-1:2016",
    "SNI IEC 61215-2:2016",
    "IEC 61730"
  ]
}'::jsonb
where component_id = '3ab27012-7792-4733-99e7-98825e763368';

-- ICA SOLAR ICA550-72HMI 550Wp Mono 2278x1134x30mm
-- source: ICA550-72HMI datasheet MKT.PRM/MY/IX/2026
update "3.0_components"
set specifications = coalesce(specifications, '{}'::jsonb) || '{
  "cell_type": "Monocrystalline",
  "number_of_cells": 144,
  "cell_configuration": "6 x 24",
  "cell_size_mm": "182 x 91",
  "bifacial": false,
  "power_stc_w": 550,
  "power_tolerance": "0 to +5 W",
  "vmp_stc_v": 42.4,
  "imp_stc_a": 12.98,
  "voc_stc_v": 50.2,
  "isc_stc_a": 13.82,
  "efficiency_percent": 21.29,
  "power_noct_w": 414.3,
  "vmp_noct_v": 39.1,
  "imp_noct_a": 10.58,
  "voc_noct_v": 46.9,
  "isc_noct_a": 11.17,
  "noct_c": "45 ± 2",
  "temp_coeff_pmax_percent_per_c": -0.35,
  "temp_coeff_voc_percent_per_c": -0.27,
  "temp_coeff_isc_percent_per_c": 0.05,
  "max_system_voltage_vdc": 1500,
  "max_series_fuse_a": 25,
  "operating_temp_range_c": "-40 to +85",
  "dimensions_l_w_h_mm": "2278 x 1134 x 30",
  "weight_kg": 29,
  "frame_material": "Anodized aluminium",
  "front_glass": "2.0mm low iron tempered glass",
  "back_glass": "2.0mm low iron tempered glass",
  "junction_box": "Split junction box (IP68, three diodes)",
  "connector_type": "MC4 compatible",
  "cable_cross_section_mm2": 4,
  "cable_length_mm": "+300 / -300 (customized length)",
  "packing_pcs_per_pallet": 31,
  "packing_pallets_per_container_40ft": 20,
  "packing_pcs_per_container_40ft": 620,
  "certifications": [
    "LSPr-072-IDN",
    "SNI IEC 61215-1-1:2016",
    "SNI IEC 61215-1:2016",
    "SNI IEC 61215-2:2016",
    "IEC 61730"
  ]
}'::jsonb
where component_id = '20d14978-a950-42ba-9c81-08f29a814449';

-- TRINA TSM-620NEG19RC.20
-- source: TSM-NEG19RC.20 datasheet TSM_EN_2024_APAC_B, 620W bin
update "3.0_components"
set specifications = coalesce(specifications, '{}'::jsonb) || '{
  "cell_type": "N-type i-TOPCon Monocrystalline",
  "number_of_cells": 132,
  "bifacial": true,
  "bifaciality_percent": 80,
  "power_stc_w": 620,
  "power_tolerance": "0 to +5 W",
  "vmp_stc_v": 41.4,
  "imp_stc_a": 14.99,
  "voc_stc_v": 49.6,
  "isc_stc_a": 15.91,
  "efficiency_percent": 23,
  "power_noct_w": 474,
  "vmp_noct_v": 38.8,
  "imp_noct_a": 12.2,
  "voc_noct_v": 47.1,
  "isc_noct_a": 12.82,
  "noct_c": "43 ± 2",
  "temp_coeff_pmax_percent_per_c": -0.29,
  "temp_coeff_voc_percent_per_c": -0.24,
  "temp_coeff_isc_percent_per_c": 0.04,
  "max_system_voltage_vdc": 1500,
  "max_series_fuse_a": 35,
  "operating_temp_range_c": "-40 to +85",
  "dimensions_l_w_h_mm": "2382 x 1134 x 30",
  "weight_kg": 33,
  "frame_material": "30mm anodized aluminium alloy",
  "front_glass": "2.0mm high transmission AR coated heat strengthened glass",
  "back_glass": "2.0mm heat strengthened glass",
  "encapsulant": "POE/EVA",
  "junction_box": "IP68 rated",
  "connector_type": "TS4 Plus / TS4",
  "cable_cross_section_mm2": 4,
  "cable_length_mm": "Portrait: 350 / 280 (length can be customized)",
  "packing_pcs_per_pallet": 36,
  "packing_pallets_per_container_40ft": 20,
  "packing_pcs_per_container_40ft": 720,
  "product_warranty_years": 12,
  "performance_warranty_years": 30,
  "certifications": [
    "IEC 61215",
    "IEC 61730",
    "IEC 61701",
    "IEC 62716",
    "UL 61730"
  ]
}'::jsonb
where component_id = '3ddfcdb1-db6e-452d-9d68-b46809d1924a';

-- TRINA TSM-715NEG21C.20
-- source: TSM-NEG21C.20 datasheet, 715W bin
update "3.0_components"
set specifications = coalesce(specifications, '{}'::jsonb) || '{
  "cell_type": "N-type i-TOPCon Monocrystalline",
  "number_of_cells": 132,
  "bifacial": true,
  "bifaciality_percent": 80,
  "power_stc_w": 715,
  "power_tolerance": "0 to +5 W",
  "vmp_stc_v": 41.1,
  "imp_stc_a": 17.4,
  "voc_stc_v": 49.2,
  "isc_stc_a": 18.44,
  "efficiency_percent": 23,
  "power_noct_w": 547,
  "vmp_noct_v": 38.7,
  "imp_noct_a": 14.14,
  "voc_noct_v": 46.7,
  "isc_noct_a": 14.86,
  "noct_c": "43 ± 2",
  "temp_coeff_pmax_percent_per_c": -0.29,
  "temp_coeff_voc_percent_per_c": -0.24,
  "temp_coeff_isc_percent_per_c": 0.04,
  "max_system_voltage_vdc": 1500,
  "max_series_fuse_a": 35,
  "operating_temp_range_c": "-40 to +70",
  "dimensions_l_w_h_mm": "2384 x 1303 x 33",
  "weight_kg": 38.3,
  "frame_material": "33mm anodized aluminium alloy",
  "front_glass": "2.0mm AR coating heat strengthened glass",
  "back_glass": "2.0mm heat strengthened glass",
  "junction_box": "IP68 rated",
  "connector_type": "TS4 / TS4 Plus / MC4 EVO2",
  "cable_cross_section_mm2": 4,
  "cable_length_mm": "Portrait: 370 / 230 (length can be customized)",
  "packing_pcs_per_pallet": 33,
  "packing_pallets_per_container_40ft": 18,
  "packing_pcs_per_container_40ft": 594,
  "product_warranty_years": 12,
  "performance_warranty_years": 30,
  "certifications": [
    "IEC 61215",
    "IEC 61730",
    "IEC 61701",
    "IEC 62716",
    "UL 61730"
  ]
}'::jsonb
where component_id = '78f4f475-1792-465d-9cea-598fc6961485';

-- TRINA TSM-720NEG21C.20
-- source: TSM-NEG21C.20 datasheet, 720W bin
update "3.0_components"
set specifications = coalesce(specifications, '{}'::jsonb) || '{
  "cell_type": "N-type i-TOPCon Monocrystalline",
  "number_of_cells": 132,
  "bifacial": true,
  "bifaciality_percent": 80,
  "power_stc_w": 720,
  "power_tolerance": "0 to +5 W",
  "vmp_stc_v": 41.3,
  "imp_stc_a": 17.44,
  "voc_stc_v": 49.4,
  "isc_stc_a": 18.49,
  "efficiency_percent": 23.2,
  "power_noct_w": 551,
  "vmp_noct_v": 38.8,
  "imp_noct_a": 14.19,
  "voc_noct_v": 46.9,
  "isc_noct_a": 14.9,
  "noct_c": "43 ± 2",
  "temp_coeff_pmax_percent_per_c": -0.29,
  "temp_coeff_voc_percent_per_c": -0.24,
  "temp_coeff_isc_percent_per_c": 0.04,
  "max_system_voltage_vdc": 1500,
  "max_series_fuse_a": 35,
  "operating_temp_range_c": "-40 to +70",
  "dimensions_l_w_h_mm": "2384 x 1303 x 33",
  "weight_kg": 38.3,
  "frame_material": "33mm anodized aluminium alloy",
  "front_glass": "2.0mm AR coating heat strengthened glass",
  "back_glass": "2.0mm heat strengthened glass",
  "junction_box": "IP68 rated",
  "connector_type": "TS4 / TS4 Plus / MC4 EVO2",
  "cable_cross_section_mm2": 4,
  "cable_length_mm": "Portrait: 370 / 230 (length can be customized)",
  "packing_pcs_per_pallet": 33,
  "packing_pallets_per_container_40ft": 18,
  "packing_pcs_per_container_40ft": 594,
  "product_warranty_years": 12,
  "performance_warranty_years": 30,
  "certifications": [
    "IEC 61215",
    "IEC 61730",
    "IEC 61701",
    "IEC 62716",
    "UL 61730"
  ]
}'::jsonb
where component_id = 'e814539a-d3d3-4133-993e-a802251fcd2d';

-- TRINA TSM-725NEG21C.20
-- source: TSM-NEG21C.20 datasheet, 725W bin
update "3.0_components"
set specifications = coalesce(specifications, '{}'::jsonb) || '{
  "cell_type": "N-type i-TOPCon Monocrystalline",
  "number_of_cells": 132,
  "bifacial": true,
  "bifaciality_percent": 80,
  "power_stc_w": 725,
  "power_tolerance": "0 to +5 W",
  "vmp_stc_v": 41.5,
  "imp_stc_a": 17.47,
  "voc_stc_v": 49.6,
  "isc_stc_a": 18.54,
  "efficiency_percent": 23.3,
  "power_noct_w": 555,
  "vmp_noct_v": 39,
  "imp_noct_a": 14.23,
  "voc_noct_v": 47.1,
  "isc_noct_a": 14.94,
  "noct_c": "43 ± 2",
  "temp_coeff_pmax_percent_per_c": -0.29,
  "temp_coeff_voc_percent_per_c": -0.24,
  "temp_coeff_isc_percent_per_c": 0.04,
  "max_system_voltage_vdc": 1500,
  "max_series_fuse_a": 35,
  "operating_temp_range_c": "-40 to +70",
  "dimensions_l_w_h_mm": "2384 x 1303 x 33",
  "weight_kg": 38.3,
  "frame_material": "33mm anodized aluminium alloy",
  "front_glass": "2.0mm AR coating heat strengthened glass",
  "back_glass": "2.0mm heat strengthened glass",
  "junction_box": "IP68 rated",
  "connector_type": "TS4 / TS4 Plus / MC4 EVO2",
  "cable_cross_section_mm2": 4,
  "cable_length_mm": "Portrait: 370 / 230 (length can be customized)",
  "packing_pcs_per_pallet": 33,
  "packing_pallets_per_container_40ft": 18,
  "packing_pcs_per_container_40ft": 594,
  "product_warranty_years": 12,
  "performance_warranty_years": 30,
  "certifications": [
    "IEC 61215",
    "IEC 61730",
    "IEC 61701",
    "IEC 62716",
    "UL 61730"
  ]
}'::jsonb
where component_id = 'ef28bf38-6d2c-4653-b813-96c9866a4491';

-- ── Every other PV module: reshape only ─────────────────────────────────────
-- The rows below are NOT rewritten. Two idempotent statements put them into
-- the same shape as the six above, so re-running this file (or running it
-- after a new module is added) is harmless.
--
-- They are emitted from lib/specSchema.ts — the alias map and the field list
-- are the same ones the app uses, so SQL and TypeScript cannot drift.
--
-- ICA SOLAR ICA100-36M 100Wp Mono 900x585x30mm — A different build from the 890x580x28 sheet — 18.3 Vmp, not 22.97.
-- ICA SOLAR ICA200-36M 200Wp Mono — Held one key. Now holds the full set, all but power unanswered.
-- ICA SOLAR ICA200-72M 200Wp Mono — NOT updated from the ICA200-72M sheet — see the note at the end.
-- ICA SOLAR ICA200-72M 200Wp Mono 1265x770x30mm — Had no specifications at all. Now has the shape, awaiting values.
-- ICA SOLAR ICA450-72HMG 450Wp Mono
-- ICA SOLAR ICA550-72HMI 550Wp Mono 2278x1134x35mm — The 35mm frame variant; the supplied sheet is the 30mm one.
-- JINKO JKM575N-72HL4-V — No datasheet on file — seven of the forty-one keys are answered.

-- 1. Column data never belongs in the blob (lib/specSchema NON_SPEC_KEYS) —
--    it would also leak a brand onto a customer-facing spec annex.
update "3.0_components"
set specifications = specifications - 'model' - 'brand' - 'selling_price_idr'
where category::text = 'pv_module'
  and specifications ?| array['model', 'brand', 'selling_price_idr'];

-- 2. Fold the spellings that predate the field set into their canonical names.
update "3.0_components"
set specifications = (specifications - 'power_tolerance_w'
     - 'glass_description'
     - 'packing_container_40ft_pcs_per_pallet'
     - 'packing_container_40ft_pallets_per_container'
     - 'packing_container_40ft_total_pcs')
  || jsonb_strip_nulls(jsonb_build_object(
       'power_tolerance', specifications -> 'power_tolerance_w',
       'front_glass', specifications -> 'glass_description',
       'packing_pcs_per_pallet', specifications -> 'packing_container_40ft_pcs_per_pallet',
       'packing_pallets_per_container_40ft', specifications -> 'packing_container_40ft_pallets_per_container',
       'packing_pcs_per_container_40ft', specifications -> 'packing_container_40ft_total_pcs'
     ))
where category::text = 'pv_module'
  and specifications ?| array['power_tolerance_w', 'glass_description', 'packing_container_40ft_pcs_per_pallet', 'packing_container_40ft_pallets_per_container', 'packing_container_40ft_total_pcs'];

-- 3. Add every declared key the row does not carry, as null. Null is an
--    answer — "the datasheet does not say" — and a query can count it. A
--    missing key cannot be counted, which is the whole reason for this file.
update "3.0_components" c
set specifications = coalesce((
      select jsonb_object_agg(k, 'null'::jsonb)
      from unnest(array['cell_type', 'number_of_cells', 'cell_configuration', 'cell_size_mm', 'bifacial', 'bifaciality_percent', 'power_stc_w', 'power_tolerance', 'vmp_stc_v', 'imp_stc_a', 'voc_stc_v', 'isc_stc_a', 'efficiency_percent', 'power_noct_w', 'vmp_noct_v', 'imp_noct_a', 'voc_noct_v', 'isc_noct_a', 'noct_c', 'temp_coeff_pmax_percent_per_c', 'temp_coeff_voc_percent_per_c', 'temp_coeff_isc_percent_per_c', 'max_system_voltage_vdc', 'max_series_fuse_a', 'operating_temp_range_c', 'dimensions_l_w_h_mm', 'weight_kg', 'frame_material', 'front_glass', 'back_glass', 'encapsulant', 'junction_box', 'connector_type', 'cable_cross_section_mm2', 'cable_length_mm', 'packing_pcs_per_pallet', 'packing_pallets_per_container_40ft', 'packing_pcs_per_container_40ft', 'product_warranty_years', 'performance_warranty_years', 'certifications']) as k
      where not (coalesce(c.specifications, '{}'::jsonb) ? k)
    ), '{}'::jsonb) || coalesce(c.specifications, '{}'::jsonb)
where c.category::text = 'pv_module';
