import { createClient } from "@supabase/supabase-js";
import { readFileSync } from "fs";
import { resolve } from "path";

// Load .env.local if present
try {
  const envFile = readFileSync(resolve(process.cwd(), ".env.local"), "utf-8");
  for (const line of envFile.split("\n")) {
    const match = line.match(/^([^#=]+)=(.*)$/);
    if (match) process.env[match[1].trim()] = match[2].trim();
  }
} catch {
  // .env.local not found, rely on environment variables
}

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;

if (!supabaseUrl || !supabaseAnonKey) {
  console.error("Missing NEXT_PUBLIC_SUPABASE_URL or NEXT_PUBLIC_SUPABASE_ANON_KEY");
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseAnonKey);

// ─────────────────────────────────────────
// PV Modules — 5 records
// ─────────────────────────────────────────
const pvModules = [
  {
    model: "ICA100-36M",
    cell_type: "Monocrystalline",
    power_stc_w: 100,
    efficiency_percent: 19.37,
    vmp_stc_v: 22.97,
    imp_stc_a: 4.36,
    voc_stc_v: 26.91,
    isc_stc_a: 4.61,
    power_tolerance: "±5%",
    temp_coeff_voc_percent_per_c: -0.32,
    temp_coeff_pmax_percent_per_c: -0.45,
    temp_coeff_isc_percent_per_c: 0.06,
    max_system_voltage_vdc: 1000,
    max_series_fuse_a: 15,
    operating_temp_range_c: "-45 to +80",
    noct_c: "45 ± 2",
    dimensions_l_w_h_mm: "890 x 580 x 28",
    weight_kg: 5.9,
    certifications: [
      "LSPr-072-IDN",
      "SNI IEC 61215-1-1:2016",
      "SNI IEC 61215-1:2016",
      "SNI IEC 61215-2:2016",
      "IEC 61730",
    ],
    selling_price_idr: 420000,
  },
  {
    model: "ICA200-72M",
    cell_type: "Monocrystalline",
    power_stc_w: 200,
    efficiency_percent: 19.7,
    vmp_stc_v: 49.04,
    imp_stc_a: 4.08,
    voc_stc_v: 56.74,
    isc_stc_a: 4.23,
    power_tolerance: "±5%",
    temp_coeff_voc_percent_per_c: -0.32,
    temp_coeff_pmax_percent_per_c: -0.45,
    temp_coeff_isc_percent_per_c: 0.06,
    max_system_voltage_vdc: 1000,
    max_series_fuse_a: 15,
    operating_temp_range_c: "-45 to +80",
    noct_c: "45 ± 2",
    dimensions_l_w_h_mm: "1328 x 765 x 28",
    weight_kg: 11.4,
    certifications: [
      "LSPr-072-IDN",
      "SNI IEC 61215-1-1:2016",
      "SNI IEC 61215-1:2016",
      "SNI IEC 61215-2:2016",
      "IEC 61730",
    ],
    selling_price_idr: 820000,
  },
  {
    model: "ICA390-72MF",
    cell_type: "Monocrystalline",
    power_stc_w: 390,
    efficiency_percent: 19.67,
    vmp_stc_v: 40.3,
    imp_stc_a: 9.68,
    voc_stc_v: 49.2,
    isc_stc_a: 10.14,
    temp_coeff_voc_percent_per_c: -0.29,
    temp_coeff_pmax_percent_per_c: -0.4,
    temp_coeff_isc_percent_per_c: 0.05,
    max_system_voltage_vdc: 1000,
    max_series_fuse_a: 15,
    operating_temp_range_c: "-40 to +85",
    noct_c: "45 ± 2",
    dimensions_l_w_h_mm: "1979 x 1002 x 35",
    weight_kg: 23,
    certifications: ["IEC 61215", "IEC 61730"],
    selling_price_idr: 1400000,
  },
  {
    model: "ICA450-72HMG",
    cell_type: "Monocrystalline",
    cell_size_mm: "166 x 83",
    number_of_cells: 144,
    cell_configuration: "6 x 24",
    power_stc_w: 450,
    power_noct_w: 338.3,
    efficiency_percent: 20.37,
    vmp_stc_v: 41.4,
    vmp_noct_v: 38.9,
    imp_stc_a: 10.87,
    imp_noct_a: 8.7,
    voc_stc_v: 50,
    voc_noct_v: 46.6,
    isc_stc_a: 11.36,
    isc_noct_a: 9.18,
    power_tolerance: "0 to +5 W",
    temp_coeff_voc_percent_per_c: -0.29,
    temp_coeff_pmax_percent_per_c: -0.36,
    temp_coeff_isc_percent_per_c: 0.05,
    max_system_voltage_vdc: 1500,
    max_series_fuse_a: 20,
    operating_temp_range_c: "-40 to +85",
    noct_c: "45 ± 2",
    dimensions_l_w_h_mm: "2108 x 1048 x 35",
    weight_kg: 24.5,
    glass_description: "3.2mm tempered low iron glass",
    frame_material: "Anodized aluminium",
    junction_box: "Split junction box (IP68, three diodes)",
    connector_type: "MC4 compatible",
    cable_cross_section_mm2: 4.0,
    cable_length_mm: "+300 / -300",
    certifications: ["IEC 61730"],
    selling_price_idr: 1450000,
  },
  {
    model: "ICA550-72HMI",
    cell_type: "Monocrystalline",
    cell_size_mm: "182 x 91",
    number_of_cells: 144,
    cell_configuration: "6 x 24",
    power_stc_w: 550,
    power_noct_w: 414.3,
    efficiency_percent: 21.29,
    vmp_stc_v: 42.4,
    vmp_noct_v: 39.1,
    imp_stc_a: 12.98,
    imp_noct_a: 10.58,
    voc_stc_v: 50.2,
    voc_noct_v: 46.9,
    isc_stc_a: 13.82,
    isc_noct_a: 11.17,
    power_tolerance: "0 to +5 W",
    temp_coeff_voc_percent_per_c: -0.27,
    temp_coeff_pmax_percent_per_c: -0.35,
    temp_coeff_isc_percent_per_c: 0.05,
    max_system_voltage_vdc: 1500,
    max_series_fuse_a: 25,
    operating_temp_range_c: "-40 to +85",
    noct_c: "45 ± 2",
    dimensions_l_w_h_mm: "2278 x 1134 x 35",
    weight_kg: 29,
    glass_description: "3.2mm tempered low iron glass",
    frame_material: "Anodized aluminium",
    junction_box: "Split junction box (IP68, three diodes)",
    connector_type: "MC4 compatible",
    cable_cross_section_mm2: 4.0,
    cable_length_mm: "+300 / -300",
    certifications: [
      "LSPr-072-IDN",
      "SNI IEC 61215-1-1:2016",
      "SNI IEC 61215-1:2016",
      "SNI IEC 61215-2:2016",
      "IEC 61730",
    ],
    selling_price_idr: 1550000,
  },
];

// ─────────────────────────────────────────
// Hybrid Inverters — 7 records
// ─────────────────────────────────────────
const hybridInverters = [
  {
    model: "SNV-GF1021",
    system_type: "Off-Grid",
    rated_output_power_w: 1000,
    surge_power_va: 2000,
    waveform: "Pure sine wave",
    efficiency_peak_percent: 93,
    transfer_time_ms: "10 (personal computers), 20 (home appliances)",
    pv_solar_charger_type: "MPPT",
    pv_max_input_power_w: 1000,
    pv_max_open_circuit_voltage_vdc: 102,
    pv_mppt_voltage_range_vdc: "30~80",
    no_of_mpp_trackers: 1,
    max_pv_input_current_a: "40",
    battery_nominal_voltage_vdc: 24,
    battery_floating_charge_voltage_vdc: 27,
    battery_overcharge_protection_vdc: 31,
    max_solar_charging_current_a: "40",
    max_ac_charging_current_a: 20,
    max_total_charging_current_a: "60",
    ac_input_voltage_range_vac: "170~280 / 90~280",
    ac_input_frequency_hz: "50/60 (auto sensing)",
    nominal_output_voltage_vac: "220",
    output_voltage_regulation: "±5%",
    phase: "1-phase",
    parallel_operation: "No",
    communication_interfaces: "USB/RS232",
    operating_temperature_range_c: "-10 to 50",
    storage_temperature_range_c: "-15 to 60",
    humidity_range_percent: "5 to 95 (non-condensing)",
    dimensions_d_w_h_mm: "88 x 225 x 320",
    weight_kg: 5,
    selling_price_idr: 3500000,
  },
  {
    model: "SNV-GH2041",
    system_type: "Hybrid",
    rated_output_power_w: 2000,
    waveform: "Pure sine wave",
    efficiency_dc_to_ac_percent: "93",
    max_conversion_efficiency_dc_ac_percent: 95,
    pv_solar_charger_type: "MPPT",
    pv_max_input_power_w: 3000,
    pv_nominal_voltage_vdc: 240,
    pv_max_open_circuit_voltage_vdc: 450,
    pv_mppt_voltage_range_vdc: "90~430",
    no_of_mpp_trackers: 1,
    max_pv_input_current_a: "13",
    battery_nominal_voltage_vdc: 48,
    max_solar_charging_current_a: "60",
    max_ac_charging_current_a: 60,
    max_total_charging_current_a: "60",
    ac_input_voltage_range_vac: "90~280 or 170~280",
    ac_input_frequency_hz: "50/60 (auto sensing)",
    max_ac_input_current_a: 30,
    nominal_output_voltage_vac: "220/230/240",
    phase: "1-phase in/1-phase out",
    parallel_operation: "Yes, up to 9 units",
    communication_interfaces: "USB, RS-232, Dry contact",
    operating_temperature_range_c: "-10 to 50",
    humidity_range_percent: "0~90 (no condensing)",
    dimensions_d_w_h_mm: "120 x 295 x 468",
    weight_kg: 11,
    selling_price_idr: 6700000,
  },
  {
    model: "SNV-GH3041",
    system_type: "Hybrid",
    rated_output_power_w: 3000,
    waveform: "Pure sine wave",
    efficiency_dc_to_ac_percent: "93",
    max_conversion_efficiency_dc_ac_percent: 95,
    pv_solar_charger_type: "MPPT",
    pv_max_input_power_w: 4000,
    pv_nominal_voltage_vdc: 360,
    pv_max_open_circuit_voltage_vdc: 450,
    pv_mppt_voltage_range_vdc: "120~430",
    no_of_mpp_trackers: 1,
    max_pv_input_current_a: "18",
    battery_nominal_voltage_vdc: 48,
    max_solar_charging_current_a: "60",
    max_ac_charging_current_a: 60,
    max_total_charging_current_a: "60",
    ac_input_voltage_range_vac: "90~280 or 170~280",
    ac_input_frequency_hz: "50/60 (auto sensing)",
    max_ac_input_current_a: 40,
    nominal_output_voltage_vac: "220/230/240",
    phase: "1-phase in/1-phase out",
    parallel_operation: "Yes, up to 9 units",
    communication_interfaces: "USB, RS-232, Dry contact",
    operating_temperature_range_c: "-10 to 50",
    humidity_range_percent: "0~90 (no condensing)",
    dimensions_d_w_h_mm: "120 x 295 x 468",
    weight_kg: 11,
    selling_price_idr: 7300000,
  },
  {
    model: "SNV-GH5042",
    system_type: "Hybrid",
    rated_output_power_w: 5000,
    waveform: "Pure sine wave",
    efficiency_dc_to_ac_percent: "93",
    max_conversion_efficiency_dc_ac_percent: 95,
    pv_solar_charger_type: "MPPT",
    pv_max_input_power_w: 6000,
    pv_nominal_voltage_vdc: 360,
    pv_max_open_circuit_voltage_vdc: 450,
    pv_mppt_voltage_range_vdc: "120~430",
    no_of_mpp_trackers: 1,
    max_pv_input_current_a: "27",
    battery_nominal_voltage_vdc: 48,
    max_solar_charging_current_a: "100",
    max_ac_charging_current_a: 100,
    max_total_charging_current_a: "100",
    ac_input_voltage_range_vac: "90~280 or 170~280",
    ac_input_frequency_hz: "50/60 (auto sensing)",
    max_ac_input_current_a: 40,
    nominal_output_voltage_vac: "220/230/240",
    phase: "1-phase in/1-phase out",
    parallel_operation: "Yes, up to 9 units",
    communication_interfaces: "USB, RS-232, Dry contact, RS485 for Lithium BMS",
    monitoring: "Inbuilt WiFi Data Logger",
    operating_temperature_range_c: "-10 to 50",
    humidity_range_percent: "0~90 (no condensing)",
    dimensions_d_w_h_mm: "140 x 295 x 468",
    weight_kg: 12,
    selling_price_idr: 9500000,
  },
  {
    model: "SNV-GH10041",
    system_type: "Hybrid",
    rated_output_power_w: 10000,
    waveform: "Pure sine wave",
    efficiency_dc_to_ac_percent: "91",
    max_conversion_efficiency_dc_ac_percent: 96,
    pv_solar_charger_type: "MPPT",
    pv_max_input_power_w: 14850,
    pv_nominal_voltage_vdc: 720,
    pv_max_open_circuit_voltage_vdc: 900,
    pv_mppt_voltage_range_vdc: "350~950",
    no_of_mpp_trackers: 2,
    max_pv_input_current_a: "18.6 per tracker",
    battery_nominal_voltage_vdc: 48,
    max_total_charging_current_a: "10~200",
    ac_input_voltage_range_vac: "170~290 (P-N)",
    ac_start_up_voltage_vac: "120~140 (P-N)",
    max_ac_input_current_a: 40,
    nominal_output_voltage_vac: "220 (P-N)/380 (P-P)",
    phase: "3-phase in/3-phase out",
    parallel_operation: "Yes, up to 6 units",
    communication_interfaces: "RS-232, USB, Dry Contact",
    intelligent_slot: "Optional SNMP, Modbus, AS-400",
    operating_temperature_range_c: "-10 to 55",
    humidity_range_percent: "0~90 (no condensing)",
    dimensions_d_w_h_mm: "167.2 x 500 x 622",
    weight_kg: 40,
    selling_price_idr: 55000000,
  },
  {
    model: "SNV-GH30081",
    system_type: "Hybrid",
    rated_output_power_w: 30000,
    waveform: "Pure sine wave",
    efficiency_dc_to_ac_percent: "97",
    max_conversion_efficiency_dc_ac_percent: 96.5,
    pv_solar_charger_type: "MPPT",
    pv_max_input_power_w: 40000,
    pv_nominal_voltage_vdc: 720,
    pv_max_open_circuit_voltage_vdc: 1000,
    pv_mppt_voltage_range_vdc: "350~900",
    no_of_mpp_trackers: 3,
    max_pv_input_current_a: "26 per MPPT",
    battery_voltage_range_vdc: "500~900",
    max_total_charging_current_a: "50",
    ac_input_voltage_range_vac: "170~280 per phase",
    ac_start_up_voltage_vac: "120~140 per phase",
    max_ac_input_current_a: 50,
    nominal_output_voltage_vac: "220 (P-N)/380 (P-P)",
    phase: "3-phase",
    parallel_operation: "Yes, up to 4 units",
    communication_interfaces: "RS-232, USB, DRY CONTACT, RS-485, Wi-Fi",
    intelligent_slot: "Optional SNMP, MODBUS, GPRS",
    operating_temperature_range_c: "-25 to 60",
    humidity_range_percent: "0~100",
    dimensions_d_w_h_mm: "255 x 660 x 750",
    weight_kg: 73,
    selling_price_idr: 89000000,
  },
  {
    model: "SNV-GHT30071",
    system_type: "Hybrid",
    rated_output_power_w: 30000,
    waveform: "Pure sine wave",
    efficiency_dc_to_ac_percent: ">91",
    max_conversion_efficiency_dc_ac_percent: 95,
    pv_solar_charger_type: "MPPT",
    pv_max_input_power_w: 45000,
    pv_nominal_voltage_vdc: 720,
    pv_max_open_circuit_voltage_vdc: 950,
    pv_mppt_voltage_range_vdc: "460~900",
    no_of_mpp_trackers: 1,
    max_pv_input_current_a: "72",
    battery_nominal_voltage_vdc: 384,
    battery_voltage_range_vdc: "384~480",
    max_total_charging_current_a: "80",
    ac_input_voltage_range_vac: "170~280 per phase",
    ac_start_up_voltage_vac: "150~170 per phase",
    max_ac_input_current_a: 43.5,
    nominal_output_voltage_vac: "220 (L-N)/380 (L-L)",
    phase: "3-phase",
    parallel_operation: "Yes, up to 4 units",
    communication_interfaces: "RS-232, USB",
    intelligent_slot: "Optional SNMP, GPRS, WIFI, Modbus",
    operating_temperature_range_c: "-10 to 55",
    humidity_range_percent: "0~90 (non-condensing)",
    dimensions_d_w_h_mm: "430 x 715 x 1021",
    weight_kg: 223,
    selling_price_idr: null,
  },
];

// ─────────────────────────────────────────
// Batteries — 3 records
// ─────────────────────────────────────────
const batteries = [
  {
    model: "LIP12100D",
    battery_type: "Lead-Acid (Deep Cycle)",
    nominal_voltage_v: 12,
    rated_capacity_ah: 100,
    energy_wh: 1200,
    max_discharge_current_a: 800,
    max_charge_current_a: 30,
    charge_voltage_cycle_v: 14.4,
    charge_voltage_float_v: 13.8,
    internal_resistance_mohm: "5",
    self_discharge_percent_per_month: "<3",
    cycle_life: "Not specified",
    operating_temp_range_charge_c: "-15 to 40",
    operating_temp_range_discharge_c: "-15 to 40",
    storage_temp_range_c: "-15 to 40",
    dimensions_l_w_h_mm: "407 x 174 x 236",
    weight_kg: 32.5,
    terminal_type: "Bolt Size 8mm",
    selling_price_idr: 2315000,
  },
  {
    model: "LIP12200D",
    battery_type: "Lead-Acid (Deep Cycle)",
    nominal_voltage_v: 12,
    rated_capacity_ah: 200,
    energy_wh: 2400,
    max_discharge_current_a: 1333,
    max_charge_current_a: 30,
    charge_voltage_cycle_v: 14.4,
    charge_voltage_float_v: 13.8,
    internal_resistance_mohm: "3",
    self_discharge_percent_per_month: "<3",
    cycle_life: "Not specified",
    operating_temp_range_charge_c: "-15 to 40",
    operating_temp_range_discharge_c: "-15 to 40",
    storage_temp_range_c: "-15 to 40",
    dimensions_l_w_h_mm: "523 x 240 x 230",
    weight_kg: 57.5,
    terminal_type: "Bolt Size 8mm",
    selling_price_idr: 4250000,
  },
  {
    model: "LIP48100LF",
    battery_type: "LiFePO4 (with BMS)",
    nominal_voltage_v: 48,
    rated_capacity_ah: 100,
    energy_wh: 4800,
    max_discharge_current_a: 100,
    max_charge_current_a: 100,
    rated_charge_current_a: 30,
    charge_voltage_v: 54,
    discharge_cut_off_voltage_v: 39,
    internal_resistance_mohm: "<=30",
    self_discharge_percent_per_month: "<3",
    cycle_life: ">=4000 @ 0.2C 80% DOD",
    configuration: "15S1P",
    operating_temp_range_charge_c: "0 to 50",
    operating_temp_range_discharge_c: "-20 to 55",
    storage_temp_range_c: "0 to 40",
    dimensions_l_w_h_mm: "450 x 483 x 133",
    weight_kg: 42,
    selling_price_idr: 15900000,
  },
];

// ─────────────────────────────────────────
// Solar Charge Controllers — 9 records
// ─────────────────────────────────────────
const solarChargeControllers = [
  {
    model: "XTRA1210N_G3",
    controller_type: "MPPT",
    rated_charge_current_a: 10,
    rated_charging_power_w: "130/12V; 260/24V",
    system_voltage_v: "12/24",
    controller_operating_voltage_range_v: "8–31",
    pv_max_voc_v: 100,
    mppt_voltage_range_v: "Battery V +2V to 72V",
    max_conversion_efficiency_percent: 98.2,
    max_load_efficiency_percent: 96.2,
    tracking_efficiency_percent: ">=99.5",
    self_consumption_ma: "<10",
    ip_rating: "IP33",
    grounding_type: "Common negative",
    operating_temperature_range_c: "-25 to 50",
    recommended_cable_mm2: "4",
    dimensions_mm: "175 x 143 x 48",
    weight_kg: 0.59,
    communication: "Bluetooth (BLE series)",
    battery_types: "Lithium, Gel, Sealed",
    certifications: "CE, IECS",
    selling_price_idr: 820000,
  },
  {
    model: "XTRA2210N_G3",
    controller_type: "MPPT",
    rated_charge_current_a: 20,
    rated_charging_power_w: "260/12V; 520/24V",
    system_voltage_v: "12/24",
    controller_operating_voltage_range_v: "8–31",
    pv_max_voc_v: 100,
    mppt_voltage_range_v: "Battery V +2V to 72V",
    max_conversion_efficiency_percent: 98.3,
    max_load_efficiency_percent: 96.4,
    tracking_efficiency_percent: ">=99.5",
    self_consumption_ma: "<10",
    ip_rating: "IP33",
    grounding_type: "Common negative",
    operating_temperature_range_c: "-25 to 50",
    recommended_cable_mm2: "6",
    dimensions_mm: "217 x 158 x 56.6",
    weight_kg: 0.97,
    communication: "Bluetooth (BLE series)",
    battery_types: "Lithium, Gel, Sealed",
    certifications: "CE, IECS",
    selling_price_idr: 1050000,
  },
  {
    model: "XTRA3210N_G3",
    controller_type: "MPPT",
    rated_charge_current_a: 30,
    rated_charging_power_w: "390/12V; 780/24V",
    system_voltage_v: "12/24",
    controller_operating_voltage_range_v: "8–31",
    pv_max_voc_v: 100,
    mppt_voltage_range_v: "Battery V +2V to 72V",
    max_conversion_efficiency_percent: 98.6,
    max_load_efficiency_percent: 96.6,
    tracking_efficiency_percent: ">=99.5",
    self_consumption_ma: "<10",
    ip_rating: "IP33",
    grounding_type: "Common negative",
    operating_temperature_range_c: "-25 to 50",
    recommended_cable_mm2: "10",
    dimensions_mm: "230 x 165 x 63",
    weight_kg: 1.3,
    communication: "Bluetooth (BLE series)",
    battery_types: "Lithium, Gel, Sealed",
    certifications: "CE, IECS",
    selling_price_idr: 1170000,
  },
  {
    model: "XTRA4210N_G3",
    controller_type: "MPPT",
    rated_charge_current_a: 40,
    rated_charging_power_w: "520/12V; 1040/24V",
    system_voltage_v: "12/24",
    controller_operating_voltage_range_v: "8–31",
    pv_max_voc_v: 100,
    mppt_voltage_range_v: "Battery V +2V to 72V",
    max_conversion_efficiency_percent: 98.6,
    max_load_efficiency_percent: 96.5,
    tracking_efficiency_percent: ">=99.5",
    self_consumption_ma: "<10",
    ip_rating: "IP33",
    grounding_type: "Common negative",
    operating_temperature_range_c: "-25 to 50",
    recommended_cable_mm2: "16",
    dimensions_mm: "255 x 185 x 67.8",
    weight_kg: 1.72,
    communication: "Bluetooth (BLE series)",
    battery_types: "Lithium, Gel, Sealed",
    certifications: "CE, IECS",
    selling_price_idr: 1500000,
  },
  {
    model: "XTRA4415N_G3",
    controller_type: "MPPT",
    rated_charge_current_a: 40,
    rated_charging_power_w: "520/12V; 1040/24V; 1560/36V; 2080/48V",
    system_voltage_v: "12/24/36/48",
    controller_operating_voltage_range_v: "8–62",
    pv_max_voc_v: 150,
    mppt_voltage_range_v: "Battery V +2V to 108V",
    max_conversion_efficiency_percent: 98.5,
    max_load_efficiency_percent: 97.2,
    tracking_efficiency_percent: ">=99.5",
    self_consumption_ma: "<10",
    ip_rating: "IP33",
    grounding_type: "Common negative",
    operating_temperature_range_c: "-25 to 45",
    recommended_cable_mm2: "16",
    dimensions_mm: "255 x 189 x 83.2",
    weight_kg: 2.6,
    communication: "Bluetooth (BLE series)",
    battery_types: "Lithium, Gel, Sealed",
    certifications: "CE, IECS",
    selling_price_idr: 1880000,
  },
  {
    model: "ET5420NC_G3",
    controller_type: "MPPT",
    rated_charge_current_a: 50,
    rated_charging_power_w: "650/12V; 1300/24V; 2600/48V",
    system_voltage_v: "12/24/48",
    controller_operating_voltage_range_v: "8–62",
    pv_max_voc_v: 200,
    mppt_voltage_range_v: "Battery V +2V to 144V",
    max_conversion_efficiency_percent: 98.3,
    tracking_efficiency_percent: ">=99.9",
    self_consumption_ma: "Low",
    ip_rating: "IP43",
    grounding_type: "Common negative",
    operating_temperature_range_c: "-25 to 60",
    recommended_cable_mm2: "16",
    dimensions_mm: "307 x 253 x 143",
    weight_kg: 5,
    communication: "RS485, CAN, BMS (via BMS-LINK), Optional Bluetooth/WiFi/4G",
    battery_types: "AGM, Gel, Flooded, LiFePO4",
    parallel_operation: "Up to 6 (CAN)",
    pv_inputs: 1,
    certifications: "CE, EMC compliant (CLASS B)",
    selling_price_idr: 3450000,
  },
  {
    model: "ET10420NC_G3",
    controller_type: "MPPT",
    rated_charge_current_a: 100,
    rated_charging_power_w: "1300/12V; 2600/24V; 5200/48V",
    system_voltage_v: "12/24/48",
    controller_operating_voltage_range_v: "8–62",
    pv_max_voc_v: 200,
    mppt_voltage_range_v: "Battery V +2V to 144V",
    max_conversion_efficiency_percent: 98.5,
    tracking_efficiency_percent: ">=99.9",
    self_consumption_ma: "Low",
    ip_rating: "IP43",
    grounding_type: "Common negative",
    operating_temperature_range_c: "-25 to 60",
    recommended_cable_mm2: "35",
    dimensions_mm: "352 x 263 x 158",
    weight_kg: 7.79,
    communication: "RS485, CAN, BMS (via BMS-LINK), Optional Bluetooth/WiFi/4G",
    battery_types: "AGM, Gel, Flooded, LiFePO4",
    parallel_operation: "Up to 6 (CAN)",
    pv_inputs: 2,
    certifications: "CE, EMC compliant (CLASS B)",
    selling_price_idr: 5500000,
  },
  {
    model: "Tracer5420AN",
    controller_type: "MPPT",
    rated_charge_current_a: 50,
    rated_charging_power_w: "625/12V; 1250/24V; 1875/36V; 2500/48V",
    system_voltage_v: "12/24/36/48",
    controller_operating_voltage_range_v: "8–68",
    pv_max_voc_v: 200,
    mppt_voltage_range_v: "Battery V +2V to 144V",
    max_conversion_efficiency_percent: 98.3,
    max_load_efficiency_percent: 97.1,
    tracking_efficiency_percent: ">=99.5",
    self_consumption_ma: "Low",
    ip_rating: "IP32 (without terminal cover)",
    grounding_type: "Common negative",
    operating_temperature_range_c: "-25 to 60",
    recommended_cable_mm2: "16",
    dimensions_mm: "261 x 216 x 119",
    weight_kg: 3.5,
    communication: "Isolated RS485 (5VDC/200mA, MODBUS)",
    battery_types: "Sealed, Gel, Flooded, User",
    parallel_operation: "Up to 8",
    battery_temp_compensation: "Yes",
    certifications: "CE (LVD EN/IEC62109, EMC EN61000-6-1/3)",
    selling_price_idr: 3500000,
  },
  {
    model: "Tracer10420AN",
    controller_type: "MPPT",
    rated_charge_current_a: 100,
    rated_charging_power_w: "1250/12V; 2500/24V; 3750/36V; 5000/48V",
    system_voltage_v: "12/24/36/48",
    controller_operating_voltage_range_v: "8–68",
    pv_max_voc_v: 200,
    mppt_voltage_range_v: "Battery V +2V to 144V",
    max_conversion_efficiency_percent: 98.5,
    tracking_efficiency_percent: ">=99.5",
    self_consumption_ma: "Low",
    ip_rating: "IP32 (without terminal cover)",
    grounding_type: "Common negative",
    operating_temperature_range_c: "-25 to 60",
    recommended_cable_mm2: "35",
    dimensions_mm: "394 x 242 x 143",
    weight_kg: 7.4,
    communication: "Isolated RS485 (5VDC/200mA, MODBUS)",
    battery_types: "Sealed, Gel, Flooded, User",
    parallel_operation: "Up to 8",
    battery_temp_compensation: "Yes",
    certifications: "CE (LVD EN/IEC62109, EMC EN61000-6-1/3)",
    selling_price_idr: 6600000,
  },
];

// ─────────────────────────────────────────
// On-Grid Inverters — 9 records
// ─────────────────────────────────────────
const onGridInverters = [
  {
    model: "SNV-GT2023SSC",
    rated_output_power_kw: 2,
    max_ac_apparent_power_kva: 2,
    max_pv_input_power_kw: 3,
    no_of_mppts: 1,
    strings_per_mppt: 1,
    pv_max_voltage_vdc: 600,
    pv_nominal_voltage_vdc: 360,
    pv_mppt_voltage_range_vdc: "70-560",
    pv_start_voltage_vdc: 80,
    max_input_current_per_mppt_a: 13,
    max_short_circuit_current_per_mppt_a: 16,
    nominal_ac_voltage_vac: "230 L-N",
    ac_grid_frequency_range_hz: "50/60 ±5",
    max_output_current_a: 9,
    power_factor_cos_phi: "0.8 leading to 0.8 lagging",
    thdi_percent: "<3",
    max_efficiency_percent: 97.5,
    euro_efficiency_percent: 97,
    surge_protection_dc_ac: "Type III",
    dc_reverse_polarity_protection: "Yes",
    ac_short_circuit_protection: "Yes",
    anti_islanding_protection: "Yes",
    output_over_current_protection: "Yes",
    dc_switch: "Yes",
    string_fault_detection: "Yes",
    insulation_detection: "Yes",
    ip_rating: "IP65",
    cooling_type: "Natural",
    operating_temperature_range_c: "-25 to +60",
    max_operating_humidity_percent: "0-100",
    max_operating_altitude_m: 2000,
    topology: "Transformerless",
    communication_interfaces: "RS485/WIFI/4G",
    display: "LCD",
    certifications: "EN/IEC62109-1/2",
    dimensions_w_h_d_mm: "290 x 390 x 126.5",
    weight_kg: 8.9,
    selling_price_idr: 5100000,
  },
  {
    model: "SNV-GT3023SSC",
    rated_output_power_kw: 3,
    max_ac_apparent_power_kva: 3,
    max_pv_input_power_kw: 4.5,
    no_of_mppts: 1,
    strings_per_mppt: 1,
    pv_max_voltage_vdc: 600,
    pv_nominal_voltage_vdc: 360,
    pv_mppt_voltage_range_vdc: "70-560",
    pv_start_voltage_vdc: 80,
    max_input_current_per_mppt_a: 13,
    max_short_circuit_current_per_mppt_a: 16,
    nominal_ac_voltage_vac: "230 L-N",
    ac_grid_frequency_range_hz: "50/60 ±5",
    max_output_current_a: 14,
    power_factor_cos_phi: "0.8 leading to 0.8 lagging",
    thdi_percent: "<3",
    max_efficiency_percent: 97.6,
    euro_efficiency_percent: 97,
    surge_protection_dc_ac: "Type III",
    dc_reverse_polarity_protection: "Yes",
    ac_short_circuit_protection: "Yes",
    anti_islanding_protection: "Yes",
    output_over_current_protection: "Yes",
    dc_switch: "Yes",
    string_fault_detection: "Yes",
    insulation_detection: "Yes",
    ip_rating: "IP65",
    cooling_type: "Natural",
    operating_temperature_range_c: "-25 to +60",
    max_operating_humidity_percent: "0-100",
    max_operating_altitude_m: 2000,
    topology: "Transformerless",
    communication_interfaces: "RS485/WIFI/4G",
    display: "LCD",
    certifications: "EN/IEC62109-1/2",
    dimensions_w_h_d_mm: "290 x 390 x 126.5",
    weight_kg: 8.9,
    selling_price_idr: 5900000,
  },
  {
    model: "SNV-GT5023DSC",
    rated_output_power_kw: 5,
    max_ac_apparent_power_kva: 5.5,
    max_pv_input_power_kw: 6.75,
    no_of_mppts: 2,
    strings_per_mppt: 1,
    pv_max_voltage_vdc: 600,
    pv_nominal_voltage_vdc: 380,
    pv_mppt_voltage_range_vdc: "80-560",
    pv_start_voltage_vdc: 100,
    max_input_current_per_mppt_a: 15,
    max_short_circuit_current_per_mppt_a: 18,
    nominal_ac_voltage_vac: "230 L-N",
    ac_grid_frequency_range_hz: "50/60 ±5",
    max_output_current_a: 24,
    power_factor_cos_phi: "0.8 leading to 0.8 lagging",
    thdi_percent: "<3",
    max_efficiency_percent: 98.3,
    euro_efficiency_percent: 97.9,
    surge_protection_dc_ac: "Type III",
    dc_reverse_polarity_protection: "Yes",
    ac_short_circuit_protection: "Yes",
    anti_islanding_protection: "Yes",
    output_over_current_protection: "Yes",
    dc_switch: "Yes",
    string_fault_detection: "Yes",
    insulation_detection: "Yes",
    ip_rating: "IP65",
    cooling_type: "Natural",
    operating_temperature_range_c: "-25 to +60",
    max_operating_humidity_percent: "0-100",
    max_operating_altitude_m: 4000,
    topology: "Transformerless",
    communication_interfaces: "RS485/WIFI/4G",
    display: "LCD",
    certifications: "EN/IEC62109-1/2",
    dimensions_w_h_d_mm: "380 x 380 x 150",
    weight_kg: 11,
    selling_price_idr: 8000000,
  },
  {
    model: "SNV-GT5023DT",
    rated_output_power_kw: 5,
    max_ac_apparent_power_kva: 5.5,
    max_pv_input_power_kw: 10,
    no_of_mppts: 2,
    strings_per_mppt: 1,
    pv_max_voltage_vdc: 1100,
    pv_nominal_voltage_vdc: 600,
    pv_mppt_voltage_range_vdc: "140-1000",
    pv_start_voltage_vdc: 180,
    max_input_current_per_mppt_a: 15,
    max_short_circuit_current_per_mppt_a: 25,
    nominal_ac_voltage_vac: "400 3L+N",
    ac_grid_frequency_range_hz: "50/60 ±5",
    max_output_current_a: 8.5,
    power_factor_cos_phi: "0.8 leading to 0.8 lagging",
    thdi_percent: "<3",
    max_efficiency_percent: 98.4,
    euro_efficiency_percent: 97.5,
    surge_protection_dc_ac: "Type II",
    dc_reverse_polarity_protection: "Yes",
    ac_short_circuit_protection: "Yes",
    anti_islanding_protection: "Yes",
    output_over_current_protection: "Yes",
    dc_switch: "Yes",
    string_fault_detection: "Yes",
    insulation_detection: "Yes",
    ip_rating: "IP65",
    cooling_type: "Natural cooling",
    operating_temperature_range_c: "-25 to +60",
    max_operating_humidity_percent: "0-100 (No condensation)",
    max_operating_altitude_m: 4000,
    topology: "Transformerless",
    communication_interfaces: "RS485/WiFi/4G",
    display: "LCD",
    certifications: "EN/IEC62109-1/2",
    dimensions_w_h_d_mm: "380 x 483 x 161",
    weight_kg: 18,
    selling_price_idr: 11000000,
  },
  {
    model: "SNV-GT1033DT",
    rated_output_power_kw: 10,
    max_ac_apparent_power_kva: 11,
    max_pv_input_power_kw: 15,
    no_of_mppts: 2,
    strings_per_mppt: 1,
    pv_max_voltage_vdc: 1100,
    pv_nominal_voltage_vdc: 600,
    pv_mppt_voltage_range_vdc: "140-1000",
    pv_start_voltage_vdc: 180,
    max_input_current_per_mppt_a: 15,
    max_short_circuit_current_per_mppt_a: 25,
    nominal_ac_voltage_vac: "400 3L+N",
    ac_grid_frequency_range_hz: "50/60 ±5",
    max_output_current_a: 16.9,
    power_factor_cos_phi: "0.8 leading to 0.8 lagging",
    thdi_percent: "<3",
    max_efficiency_percent: 98.6,
    euro_efficiency_percent: 98.1,
    surge_protection_dc_ac: "Type II",
    dc_reverse_polarity_protection: "Yes",
    ac_short_circuit_protection: "Yes",
    anti_islanding_protection: "Yes",
    output_over_current_protection: "Yes",
    dc_switch: "Yes",
    string_fault_detection: "Yes",
    insulation_detection: "Yes",
    ip_rating: "IP65",
    cooling_type: "Natural cooling",
    operating_temperature_range_c: "-25 to +60",
    max_operating_humidity_percent: "0-100 (No condensation)",
    max_operating_altitude_m: 4000,
    topology: "Transformerless",
    communication_interfaces: "RS485/WiFi/4G",
    display: "LCD",
    certifications: "EN/IEC62109-1/2",
    dimensions_w_h_d_mm: "380 x 483 x 161",
    weight_kg: 18,
    selling_price_idr: 12800000,
  },
  {
    model: "SNV-GT3033TT",
    rated_output_power_kw: 30,
    max_ac_apparent_power_kva: 33,
    no_of_mppts: 3,
    strings_per_mppt: 2,
    pv_max_voltage_vdc: 1100,
    pv_nominal_voltage_vdc: 620,
    pv_mppt_voltage_range_vdc: "200-1000",
    pv_start_voltage_vdc: 250,
    max_input_current_per_mppt_a: 30,
    max_short_circuit_current_per_mppt_a: 40,
    nominal_ac_voltage_vac: "400 3L+N+PE",
    ac_grid_frequency_range_hz: "50/60 ±5",
    max_output_current_a: 47.8,
    power_factor_cos_phi: "0.8 leading to 0.8 lagging",
    thdi_percent: "<=3",
    max_efficiency_percent: 98.7,
    euro_efficiency_percent: 98.4,
    surge_protection_dc_ac: "Type II",
    dc_reverse_polarity_protection: "Yes",
    ac_short_circuit_protection: "Yes",
    anti_islanding_protection: "Yes",
    output_over_current_protection: "Yes",
    dc_switch: "Yes",
    string_fault_detection: "Yes",
    insulation_detection: "Yes",
    ip_rating: "IP66",
    cooling_type: "Fan cooling",
    operating_temperature_range_c: "-25 to +60",
    max_operating_humidity_percent: "0-100 (No condensation)",
    max_operating_altitude_m: 4000,
    topology: "Transformerless",
    communication_interfaces: "RS485 standard, WiFi or Ethernet (optional)",
    display: "LCD",
    certifications: "EN/IEC62109-1;EN/IEC62109-2;IEC61683;IEC61727",
    dimensions_w_h_d_mm: "380 x 483 x 223",
    weight_kg: 25.5,
    selling_price_idr: 32300000,
  },
  {
    model: "SNV-GT5033QT",
    rated_output_power_kw: 50,
    max_ac_apparent_power_kva: 55,
    no_of_mppts: 4,
    strings_per_mppt: 2,
    pv_max_voltage_vdc: 1100,
    pv_nominal_voltage_vdc: 650,
    pv_mppt_voltage_range_vdc: "200-1000",
    pv_start_voltage_vdc: 250,
    max_input_current_per_mppt_a: 32,
    max_short_circuit_current_per_mppt_a: 48,
    nominal_ac_voltage_vac: "400 3L+N+PE",
    ac_grid_frequency_range_hz: "50/60 ±5",
    power_factor_cos_phi: "0.8 leading to 0.8 lagging",
    thdi_percent: "<=3",
    max_efficiency_percent: 98.5,
    euro_efficiency_percent: 98.2,
    surge_protection_dc_ac: "Type II",
    dc_reverse_polarity_protection: "Yes",
    ac_short_circuit_protection: "Yes",
    anti_islanding_protection: "Yes",
    output_over_current_protection: "Yes",
    dc_switch: "Yes",
    string_fault_detection: "Yes",
    insulation_detection: "Yes",
    ip_rating: "IP66",
    cooling_type: "Fan cooling",
    operating_temperature_range_c: "-25 to +60",
    max_operating_humidity_percent: "0-100 (No condensation)",
    max_operating_altitude_m: 4000,
    topology: "Transformerless",
    communication_interfaces: "RS485 standard, WiFi or Ethernet (optional)",
    display: "LCD",
    certifications: "EN/IEC62109-1;EN/IEC62109-2",
    dimensions_w_h_d_mm: "515 x 585 x 287",
    weight_kg: 51,
    selling_price_idr: 40000000,
  },
  {
    model: "SNV-GT6033QT",
    rated_output_power_kw: 60,
    max_ac_apparent_power_kva: 66,
    no_of_mppts: 4,
    strings_per_mppt: 2,
    pv_max_voltage_vdc: 1100,
    pv_nominal_voltage_vdc: 650,
    pv_mppt_voltage_range_vdc: "200-1000",
    pv_start_voltage_vdc: 250,
    max_input_current_per_mppt_a: 32,
    max_short_circuit_current_per_mppt_a: 48,
    nominal_ac_voltage_vac: "400 3L+N+PE",
    ac_grid_frequency_range_hz: "50/60 ±5",
    max_output_current_a: 95.6,
    power_factor_cos_phi: "0.8 leading to 0.8 lagging",
    thdi_percent: "<=3",
    max_efficiency_percent: 98.5,
    euro_efficiency_percent: 98.2,
    surge_protection_dc_ac: "Type II",
    dc_reverse_polarity_protection: "Yes",
    ac_short_circuit_protection: "Yes",
    anti_islanding_protection: "Yes",
    output_over_current_protection: "Yes",
    dc_switch: "Yes",
    string_fault_detection: "Yes",
    insulation_detection: "Yes",
    ip_rating: "IP66",
    cooling_type: "Fan cooling",
    operating_temperature_range_c: "-25 to +60",
    max_operating_humidity_percent: "0-100 (No condensation)",
    max_operating_altitude_m: 4000,
    topology: "Transformerless",
    communication_interfaces: "RS485 standard, WiFi or Ethernet (optional)",
    display: "LCD",
    certifications: "EN/IEC62109-1;EN/IEC62109-2",
    dimensions_w_h_d_mm: "515 x 585 x 287",
    weight_kg: 51,
    selling_price_idr: null,
  },
  {
    model: "SNV-GT8033QT",
    rated_output_power_kw: 80,
    max_ac_apparent_power_kva: 88,
    no_of_mppts: 4,
    strings_per_mppt: 3,
    pv_max_voltage_vdc: 1100,
    pv_nominal_voltage_vdc: 650,
    pv_mppt_voltage_range_vdc: "200-1000",
    pv_start_voltage_vdc: 250,
    max_input_current_per_mppt_a: 45,
    max_short_circuit_current_per_mppt_a: 60,
    nominal_ac_voltage_vac: "400 3L+N+PE",
    ac_grid_frequency_range_hz: "50/60 ±5",
    max_output_current_a: 127.5,
    power_factor_cos_phi: "0.8 leading to 0.8 lagging",
    thdi_percent: "<=3",
    max_efficiency_percent: 98.6,
    euro_efficiency_percent: 98.3,
    surge_protection_dc_ac: "Type II",
    dc_reverse_polarity_protection: "Yes",
    ac_short_circuit_protection: "Yes",
    anti_islanding_protection: "Yes",
    output_over_current_protection: "Yes",
    dc_switch: "Yes",
    string_fault_detection: "Yes",
    insulation_detection: "Yes",
    ip_rating: "IP66",
    cooling_type: "Fan cooling",
    operating_temperature_range_c: "-25 to +60",
    max_operating_humidity_percent: "0-100 (No condensation)",
    max_operating_altitude_m: 4000,
    topology: "Transformerless",
    communication_interfaces: "RS485 standard, WiFi or Ethernet (optional)",
    display: "LCD",
    certifications: "EN/IEC62109-1;EN/IEC62109-2",
    dimensions_w_h_d_mm: "515 x 585 x 287",
    weight_kg: 55,
    selling_price_idr: 55000000,
  },
];

// ─────────────────────────────────────────
// Seed function
// ─────────────────────────────────────────
async function seed() {
  console.log("🌱 Starting database seed...\n");

  // Seed PV Modules
  console.log("📦 Seeding PV Modules...");
  const { error: pvError } = await supabase
    .from("pv_modules")
    .upsert(pvModules, { onConflict: "model" });
  if (pvError) {
    console.error("❌ Error seeding PV Modules:", pvError.message);
  } else {
    console.log(`✅ ${pvModules.length} PV Modules seeded`);
  }

  // Seed Hybrid Inverters
  console.log("\n📦 Seeding Hybrid Inverters...");
  const { error: hiError } = await supabase
    .from("hybrid_inverters")
    .upsert(hybridInverters, { onConflict: "model" });
  if (hiError) {
    console.error("❌ Error seeding Hybrid Inverters:", hiError.message);
  } else {
    console.log(`✅ ${hybridInverters.length} Hybrid Inverters seeded`);
  }

  // Seed Batteries
  console.log("\n📦 Seeding Batteries...");
  const { error: batError } = await supabase
    .from("batteries")
    .upsert(batteries, { onConflict: "model" });
  if (batError) {
    console.error("❌ Error seeding Batteries:", batError.message);
  } else {
    console.log(`✅ ${batteries.length} Batteries seeded`);
  }

  // Seed Solar Charge Controllers
  console.log("\n📦 Seeding Solar Charge Controllers...");
  const { error: sccError } = await supabase
    .from("solar_charge_controllers")
    .upsert(solarChargeControllers, { onConflict: "model" });
  if (sccError) {
    console.error("❌ Error seeding Solar Charge Controllers:", sccError.message);
  } else {
    console.log(`✅ ${solarChargeControllers.length} Solar Charge Controllers seeded`);
  }

  // Seed On-Grid Inverters
  console.log("\n📦 Seeding On-Grid Inverters...");
  const { error: ogiError } = await supabase
    .from("on_grid_inverters")
    .upsert(onGridInverters, { onConflict: "model" });
  if (ogiError) {
    console.error("❌ Error seeding On-Grid Inverters:", ogiError.message);
  } else {
    console.log(`✅ ${onGridInverters.length} On-Grid Inverters seeded`);
  }

  const total =
    pvModules.length +
    hybridInverters.length +
    batteries.length +
    solarChargeControllers.length +
    onGridInverters.length;

  console.log(`\n🎉 Seed complete! Total records: ${total}`);
}

seed().catch(console.error);
