/**
 * Turn a category's datasheet transcriptions into a migration.
 *
 * Shared by every category script (PV modules, inverter chargers, and the
 * batteries and charge controllers to come) so the SQL shape is written once.
 * Everything is emitted FROM lib/specSchema.ts — the field list, the alias map,
 * the non-spec keys — so a migration can never disagree with the app.
 *
 * Three statements, all idempotent, so re-running a file (or running it after a
 * new item is added to the category) is harmless:
 *
 *   1. strip column data that must never live in the blob
 *   2. fold pre-field-set spellings into their canonical names
 *   3. add every declared key the row does not carry, as null
 *
 * Then one MERGE per datasheet row: only the keys the document states, so the
 * statement reads as the document does and re-running it changes nothing.
 */
import { conformSpecs, CATEGORY_SPEC_FIELDS, CATEGORY_ALIASES, NON_SPEC_KEYS } from '../../lib/specSchema.ts';

const q = (s) => `'${String(s).replace(/'/g, "''")}'`;

export function emitSpecSql({ category, title, why, rows, conformOnly = [] }) {
  const FIELDS = CATEGORY_SPEC_FIELDS[category];
  if (!FIELDS) throw new Error(`no declared field set for ${category}`);
  const ALIASES = Object.entries(CATEGORY_ALIASES[category] ?? {}).filter(([from, r]) => from !== r.to);
  const out = [];

  out.push(`-- ${title}
--
-- GENERATED by the script named at the end of this file — edit that, re-run
-- it, do not hand-patch this.
--
-- ${why}
--
-- Every ${category} row ends up with the same ${FIELDS.length} keys. A value the
-- datasheet does not state is null, which a query can count; a MISSING key
-- cannot be counted, and that is the whole point of a declared field set.`);

  for (const r of rows) {
    const stated = Object.fromEntries(
      Object.entries(conformSpecs(category, r.specs)).filter(([, v]) => v !== null));
    out.push(`
-- ${r.label}
-- source: ${r.source}${r.note ? `\n-- note: ${r.note}` : ''}
update "3.0_components"
set specifications = coalesce(specifications, '{}'::jsonb) || ${q(JSON.stringify(stated, null, 2))}::jsonb
where component_id = '${r.id}';`);
  }

  out.push(`
-- ── Every other ${category}: reshape only, values untouched ──${conformOnly.length ? `\n--\n-- ${conformOnly.join('\n-- ')}` : ''}

-- 1. Column data never belongs in the blob (lib/specSchema NON_SPEC_KEYS) — it
--    would also leak a brand onto a customer-facing spec annex.
update "3.0_components"
set specifications = specifications ${NON_SPEC_KEYS.map((k) => `- ${q(k)}`).join(' ')}
where category::text = ${q(category)}
  and specifications ?| array[${NON_SPEC_KEYS.map(q).join(', ')}];`);

  if (ALIASES.length) {
    out.push(`
-- 2. Fold the spellings that predate the field set into their canonical names.
update "3.0_components"
set specifications = (specifications ${ALIASES.map(([from]) => `- ${q(from)}`).join(' ')})
  || jsonb_strip_nulls(jsonb_build_object(
${ALIASES.map(([from, rule]) => `       ${q(rule.to)}, specifications -> ${q(from)}`).join(',\n')}
     ))
where category::text = ${q(category)}
  and specifications ?| array[${ALIASES.map(([from]) => q(from)).join(', ')}];`);
  }

  out.push(`
-- ${ALIASES.length ? 3 : 2}. Add every declared key the row does not carry, as null.
update "3.0_components" c
set specifications = coalesce((
      select jsonb_object_agg(k, 'null'::jsonb)
      from unnest(array[${FIELDS.map(q).join(', ')}]) as k
      where not (coalesce(c.specifications, '{}'::jsonb) ? k)
    ), '{}'::jsonb) || coalesce(c.specifications, '{}'::jsonb)
where c.category::text = ${q(category)};`);

  return out.join('\n');
}
